import {useEffect,useMemo,useRef,useState} from 'react';
import {Download,Info,Lock,RefreshCw} from 'lucide-react';
import {BleApiService,BleDatasetDetail} from '../../../app/services/bleApi';
import {failOperation,finishOperation,startOperation,updateOperation} from '../../../app/operations/operationTelemetry';

const api=new BleApiService();
type Def={label?:string;name?:string;human?:string;definition?:string;demonstrates?:string;does_not_demonstrate?:string;next?:string};
const humanTask:Record<string,string>={ble_activity:'Detección de actividad BLE',crc_valid_packets:'Paquetes BLE CRC-valid',windows_b200_corroboration:'Corroboración Windows–B200',logical_device_identification:'Identificación lógica del dispositivo',rf_fingerprint_preparation:'Preparación experimental para fingerprint RF'};
const humanState:Record<string,string>={not_ready:'No preparado',partially_prepared:'Preparación parcial',completed:'Completada',pending:'Pendiente',loss_detected:'Pérdidas detectadas',clean:'Limpia',PASSED:'Superada',PASSED_SINGLE_RUN:'Superada en una ejecución',PENDING:'Pendiente',NOT_VALIDATED:'No validado',NOT_READY:'No preparado',READY:'Preparado',quarantine:'Cuarentena',accepted:'Aceptados',incomplete:'Incompletos',complete:'Completos',historical_session_imported:'Sesión histórica importada'};
const scientificLabels:Record<string,string>={positive_e4_campaign:'Campaña positiva E4',exploratory_e2_campaign:'Campaña exploratoria E2',declared_negative_control:'Control negativo declarado',false_target_attributions_in_negative_controls:'Atribuciones falsas al objetivo',negative_control_with_active_positive_reference:'Control negativo reforzado',clean_positive_capture:'Captura positiva limpia',clean_negative_capture:'Captura negativa limpia',training_ready_examples:'Ejemplos preparados para entrenamiento',fingerprinting:'Fingerprinting'};
const matrixColumns:[string,string][]=[['device_model','Modelo'],['physical_unit_id','Unidad física'],['day','Día'],['planned_session','Sesión'],['channel','Canal'],['distance','Distancia'],['orientation','Orientación'],['location','Ubicación'],['execution_state','Ejecución'],['observed_evidence_level','Nivel máximo observado'],['quality_state','Calidad'],['required_duration_seconds','Duración requerida'],['executed_duration_seconds','Duración ejecutada'],['metadata_status','Metadatos experimentales'],['protocol_conformant','Conformidad con protocolo'],['dataset_accepted','Aceptada para dataset'],['examples_state','Estado de los ejemplos'],['conformity_reason','Motivo']];
const human=(value:unknown)=>humanState[String(value)]||String(value??'—');

function Explain({label,definition,value}: {label:string;definition?:Def;value?:string}){
 const [open,setOpen]=useState(false),ref=useRef<HTMLSpanElement>(null);
 useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==='Escape'&&setOpen(false);document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[]);
 const toggle=(event:React.KeyboardEvent|React.MouseEvent)=>{if('key'in event&&event.key!=='Enter'&&event.key!==' ')return;event.preventDefault();setOpen(x=>!x)};
 return <span ref={ref} className="relative inline-flex" onMouseEnter={()=>setOpen(true)} onMouseLeave={()=>setOpen(false)} onFocus={()=>setOpen(true)} onBlur={event=>{if(!ref.current?.contains(event.relatedTarget as Node))setOpen(false)}}><button type="button" aria-expanded={open} aria-haspopup="dialog" onClick={toggle} onKeyDown={toggle} className="inline-flex items-center gap-1 rounded underline decoration-dotted underline-offset-4 focus:outline-none focus:ring-2 focus:ring-sky-400">{label}<Info className="h-3 w-3 opacity-60"/></button>{open&&<span role="dialog" aria-label={`Explicación: ${label}`} tabIndex={0} className="absolute left-0 top-full z-50 mt-2 w-80 rounded-lg border border-sky-400/40 bg-slate-950 p-4 text-left text-xs leading-5 text-slate-200 shadow-2xl" onMouseEnter={()=>setOpen(true)} onMouseLeave={()=>setOpen(false)}><b className="block text-sm text-sky-300">{definition?.label||definition?.name||definition?.human||label}</b>{value&&<span className="mt-1 block text-emerald-300">Aplicado aquí: {value}</span>}<span className="mt-2 block">{definition?.definition||'Definición científica versionada no disponible.'}</span>{definition?.demonstrates&&<span className="mt-2 block"><b>Demuestra:</b> {definition.demonstrates}</span>}{definition?.does_not_demonstrate&&<span className="mt-1 block"><b>No demuestra:</b> {definition.does_not_demonstrate}</span>}{definition?.next&&<span className="mt-1 block"><b>Nivel siguiente:</b> {definition.next}</span>}</span>}</span>;
}
function Card({label,value,definition}:{label:string;value:unknown;definition?:Def}){return <div className="rounded-lg border border-slate-700 p-3"><div className="text-xs text-slate-400"><Explain label={label} definition={definition} value={String(value??'—')}/></div><div className="mt-1 text-xl font-semibold">{String(value??'—')}</div></div>}

export default function BleDatasetStudio(){
 const [detail,setDetail]=useState<BleDatasetDetail|null>(null),[defs,setDefs]=useState<Record<string,unknown>>({}),[sessions,setSessions]=useState<{session_id:string;state:string;target_address?:string}[]>([]),[selectedSession,setSelectedSession]=useState(''),[split,setSplit]=useState('session'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[localProgress,setLocalProgress]=useState<{phase:string;percent?:number}|null>(null);
 const load=async()=>{setBusy(true);try{const [data,definitions,history]=await Promise.all([api.dataset('BLE-EVIDENCE-DS01'),api.datasetDefinitions(),api.hybridSessions()]);setDetail(data);setDefs(definitions);setSessions(history.filter(x=>x.state==='completed'));if(!selectedSession&&history.length)setSelectedSession(history.find(x=>x.state==='completed')?.session_id||'')}catch(error){const technical=error instanceof Error?error.message:'';setMessage(technical.includes('404')?'El backend activo es anterior a Dataset Studio. Reinicie con start_unified.ps1 para cargar las rutas nuevas.':technical||'Dataset Studio no disponible. Reinicie el backend.')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const glossary=((defs.ble_scientific_glossary as {terms?:Record<string,Def>})?.terms)||{},levels=((defs.evidence_level_definitions as {levels?:Record<string,Def>})?.levels)||{},qualityDefs=((defs.dataset_quality_definitions as {states?:Record<string,Def>})?.states)||{};
 const manifest=detail?.manifest,protocol=detail?.protocol||{},metrics=detail?.quality?.metrics||{},warnings=detail?.quality?.warnings||[],scientificStatus=detail?.quality?.scientific_status||{};
 const ingest=async()=>{if(!selectedSession||!manifest)return;const operationId=`dataset-ingest:${selectedSession}`;setBusy(true);setMessage('');setLocalProgress({phase:'Leyendo ráfagas, paquetes y calidad',percent:10});startOperation({operationId,kind:'processing',title:'Generando ejemplos del dataset',phase:'Leyendo evidencias de la sesión',progressPercent:10,target:selectedSession,estimatedTotalSeconds:15,detail:`Dataset ${manifest.dataset_id} · no inicia una captura nueva`});try{updateOperation(operationId,{phase:'Aplicando niveles E0–E4 y cuarentena',progressPercent:45});setLocalProgress({phase:'Aplicando evidencia y exclusiones',percent:45});const next=await api.ingestDataset(manifest.dataset_id,manifest.version,{hybrid_session_id:selectedSession,day:1,planned_session:1});updateOperation(operationId,{phase:'Generando datasheet, métricas y SHA-256',progressPercent:90,processedItems:next.examples.length,totalItems:next.examples.length});setLocalProgress({phase:'Generando documentación e integridad',percent:90});setDetail(next);setMessage(`Sesión transformada: ${next.examples.length} ejemplos auditables.`);finishOperation(operationId,`${next.examples.length} ejemplos procesados`);setLocalProgress({phase:'Completado',percent:100})}catch(error){const text=error instanceof Error?error.message:'No se pudo ingerir.';setMessage(text);failOperation(operationId,text);setLocalProgress({phase:'Error'})}finally{setBusy(false);window.setTimeout(()=>setLocalProgress(null),2500)}};
 const freeze=async()=>{if(!manifest)return;setDetail(await api.freezeDataset(manifest.dataset_id,manifest.version));setMessage('Protocolo congelado; cualquier cambio requerirá una versión nueva.')};
 const createSplit=async()=>{if(!manifest)return;await api.splitDataset(manifest.dataset_id,manifest.version,split);await load();setMessage('Split generado por grupos independientes; comprobación de fuga superada.')};
 const examplesByState=useMemo(()=>Object.entries((metrics.exclusion_reasons as Record<string,number>)||{}),[metrics]);
 if(!detail)return <div className="rounded-xl border border-slate-700 p-6"><b>Dataset Studio</b><p className="mt-2 text-sm text-slate-400">{message||'Cargando metodología y evidencias…'}</p></div>;
 return <div className="space-y-4">
  <section className="rounded-xl border border-violet-500/40 bg-slate-900 p-5"><div className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Dataset Studio</div><h2 className="text-xl font-semibold">Generador de datasets RF verificables</h2><div className="mt-2 text-sm text-slate-300"><Explain label="IQ" definition={glossary.iq}/> + <Explain label="procedencia" definition={glossary.provenance}/> + calidad + confianza + <Explain label="evidencia verificable" definition={glossary.verifiable_evidence}/></div></section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Dataset" value={`${manifest?.dataset_id} · v${manifest?.version}`} definition={glossary.provenance}/><Card label="Condiciones planificadas" value={manifest?.campaigns_planned}/><Card label="Condiciones ejecutadas" value={`${String(manifest?.conditions_executed??0)}/${String(manifest?.campaigns_planned??0)}`}/><Card label="Condiciones conformes" value={`${String(manifest?.conditions_protocol_conformant??0)}/${String(manifest?.campaigns_planned??0)}`}/><Card label="Condiciones históricas no conformes" value={manifest?.conditions_historical_nonconformant}/><Card label="Condiciones aceptadas" value={`${String(manifest?.conditions_scientifically_accepted??0)}/${String(manifest?.campaigns_planned??0)}`}/><Card label="Sesiones independientes" value={manifest?.independent_sessions}/><Card label="Ejemplos generados" value={manifest?.examples_generated}/><Card label="Ejemplos incluidos" value={manifest?.examples_included}/><Card label="Ejemplos en cuarentena" value={manifest?.examples_quarantined}/><Card label="Nivel máximo observado" value={manifest?.maximum_evidence_level} definition={levels[manifest?.maximum_evidence_level||'E0']}/><Card label="Split" value={human(manifest?.split_status)}/><Card label="Entrenamiento" value={human(manifest?.training_readiness)}/><Card label="Fingerprinting" value={human(String(manifest?.fingerprinting).toUpperCase())} definition={levels.E5}/><Card label="Duración requerida" value={`${String(protocol.duration_seconds??30)} s`}/></section>
  <p className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-100">La metodología ya produjo evidencia positiva, exploratoria y negativa. Los datos históricos permanecen en cuarentena y no cumplen todavía el protocolo congelado de 30 segundos ni los requisitos de calidad.</p>
  <section className="rounded-xl border border-slate-700 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="max-w-4xl"><h3 className="font-semibold"><Explain label="Protocolo de campaña" definition={glossary.frozen_protocol}/></h3><div className="mt-3 text-xs uppercase tracking-wide text-slate-400">Pregunta científica</div><p className="mt-1 text-sm text-slate-200">{detail.quality.research_question_display||String(protocol.research_question||'No documentada')}</p><div className="mt-3 grid gap-3 md:grid-cols-3"><div><div className="text-xs text-slate-400">Nivel mínimo de evidencia</div><b>{String(protocol.minimum_evidence_level)}</b></div><div><div className="text-xs text-slate-400">Criterios de calidad</div><pre className="mt-1 whitespace-pre-wrap text-xs text-slate-300">{JSON.stringify(protocol.quality_requirements??{},null,2)}</pre></div><div><div className="text-xs text-slate-400">Criterios de aceptación</div><ul className="mt-1 list-disc pl-4 text-xs text-slate-300">{((protocol.acceptance_criteria as unknown[])||[]).map((x,i)=><li key={i}>{String(x)}</li>)}</ul></div></div><p className="mt-3 text-xs text-slate-400">Propósito: {humanTask[String(protocol.intended_task)]||String(protocol.intended_task)} · Canales {String(protocol.channels)} · {String(protocol.sample_rate_sps)} S/s · {String(protocol.bandwidth_hz)} Hz · {String(protocol.gain_db)} dB</p></div>{!protocol.frozen?<button disabled={busy} onClick={()=>void freeze()} className="inline-flex items-center gap-2 rounded bg-violet-700 px-3 py-2 text-sm"><Lock className="h-4 w-4"/>Congelar protocolo</button>:<span className="rounded bg-emerald-500/15 px-3 py-2 text-sm text-emerald-300">Protocolo congelado</span>}</div></section>
  <section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold">Incorporar una campaña híbrida existente</h3><p className="mt-1 text-xs text-slate-400">Generar ejemplos procesa una sesión terminada. Para leer datos nuevos del IoT, realiza antes una captura híbrida de {String(protocol.duration_seconds??30)} s con el dispositivo como objetivo.</p><div className="mt-3 flex flex-wrap gap-2"><select value={selectedSession} onChange={e=>setSelectedSession(e.target.value)} className="min-w-80 rounded bg-slate-800 p-2 text-sm">{sessions.map(s=><option key={s.session_id} value={s.session_id}>{s.session_id} · {s.target_address||'general'}</option>)}</select><button disabled={busy||!protocol.frozen} onClick={()=>void ingest()} className="rounded bg-sky-700 px-3 py-2 text-sm disabled:opacity-40">Generar ejemplos</button><button onClick={()=>void load()} className="rounded border border-slate-600 p-2" aria-label="Actualizar"><RefreshCw className="h-4 w-4"/></button></div>{localProgress&&<div className="mt-3 rounded border border-sky-500/30 bg-sky-500/10 p-3"><div className="flex justify-between text-sm"><span>{localProgress.phase}</span><b>{localProgress.percent==null?'—':`${localProgress.percent}%`}</b></div><div className="mt-2 h-2 overflow-hidden rounded bg-slate-800"><div className="h-full bg-sky-500 transition-all" style={{width:`${localProgress.percent??15}%`}}/></div></div>}{message&&<p className="mt-2 text-sm text-sky-300">{message}</p>}</section>
  <section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold">Matriz experimental: ejecución, evidencia y aceptación</h3><div className="mt-3 max-h-96 overflow-auto"><table className="min-w-[1800px] text-left text-xs"><thead><tr>{matrixColumns.map(([key,label])=><th key={key} className="p-2">{label==='Unidad física'?<Explain label={label} definition={glossary.physical_unit}/>:label}</th>)}</tr></thead><tbody>{detail.matrix.map((r,i)=><tr key={i} className="border-t border-slate-800">{matrixColumns.map(([key])=><td key={key} className="p-2">{key==='protocol_conformant'||key==='dataset_accepted'?(r[key]==null?'—':r[key]?'Sí':'No'):key==='required_duration_seconds'||key==='executed_duration_seconds'?(r[key]==null?'—':`${String(r[key])} s`):key==='distance'||key==='orientation'||key==='location'?(r[key]&&String(r[key]).toLowerCase()!=='documentar'?String(r[key]):'No documentada'):human(r[key])}</td>)}</tr>)}</tbody></table></div></section>
  <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold">Composición, correlación y calidad</h3><div className="mt-3 grid grid-cols-2 gap-2"><Card label="Tasa CRC válida" value={`${String(metrics.crc_yield_percent??0)} %`} definition={{definition:`${detail.examples.filter(x=>x.crc_valid).length} paquetes CRC válidos / ${detail.examples.length} ejemplos. No mide identidad física.`}}/><Card label="Tasa ráfaga → coincidencia fuerte" value={`${String(metrics.burst_to_strong_match_numerator??0)} / ${String(metrics.burst_to_strong_match_denominator??0)} = ${String(metrics.burst_to_strong_match_percent??0)} %`}/><Card label="Tasa sobre advertisements elegibles" value={`${String(metrics.eligible_correlation_numerator??0)} / ${String(metrics.eligible_correlation_denominator??0)} = ${String(metrics.eligible_correlation_percent??0)} %`} definition={{definition:'El denominador contiene advertisements BLE CRC-válidos elegibles; SCAN_REQ no se considera advertisement.'}}/><Card label="Overflows" value={metrics.overflows}/><Card label="Discontinuidades" value={metrics.discontinuities}/><Card label="Intervalos exactos disponibles" value={metrics.loss_intervals_available?'Sí':'No'}/><Card label="Solapamientos de overflow demostrados" value={metrics.examples_overlapping_overflow}/><Card label="Solapamientos de discontinuidad demostrados" value={metrics.examples_overlapping_discontinuity}/><Card label="Ejemplos localmente continuos demostrados" value={metrics.examples_locally_continuous}/></div><p className="mt-3 rounded border border-slate-700 p-3 text-xs text-slate-300"><b>Política aplicada:</b> {String(metrics.loss_localization_policy||'No documentada')}</p>{warnings.length>0&&<div className="mt-3 rounded bg-amber-500/10 p-3 text-sm text-amber-300">Advertencias: {warnings.join(' · ')}</div>}</section><section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold">Inclusión y cuarentena</h3><div className="mt-3 space-y-2">{examplesByState.map(([state,count])=><div key={state} className="flex justify-between rounded border border-slate-800 p-2 text-sm"><Explain label={qualityDefs[state]?.human||state} definition={qualityDefs[state]} value={`${count} ejemplos`}/><b>{count}</b></div>)}{!examplesByState.length&&<p className="text-sm text-slate-400">Aún no hay ejemplos.</p>}</div></section></div>
  <section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold"><Explain label="Split y comprobación de fuga" definition={glossary.leakage}/></h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Estado del split" value={human(detail.split.split_status||'NOT_READY')}/><Card label="Política prevista" value="Agrupación por sesión"/><Card label="Comprobación de fuga estructural" value={human(detail.split.split_integrity_check||detail.split.leakage_check||'PENDING')}/><Card label="Utilizable para entrenamiento" value={detail.split.training_usable?'Sí':'No'}/></div><p className="mt-2 text-sm text-slate-400">Motivo: {detail.split.reason==='no_accepted_examples'?'cero ejemplos aceptados':human(detail.split.reason)}</p><div className="mt-3 flex flex-wrap gap-2"><select value={split} onChange={e=>setSplit(e.target.value)} className="rounded bg-slate-800 p-2 text-sm">{[['session','por sesión'],['day','por día'],['physical_unit','por unidad física'],['channel','por canal'],['location','por ubicación'],['receiver','por receptor']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><button disabled={!manifest?.examples_included} onClick={()=>void createSplit()} className="rounded bg-emerald-700 px-3 py-2 text-sm disabled:opacity-40">Generar split</button></div></section>
  <section className="rounded-xl border border-slate-700 p-5"><h3 className="font-semibold">Exportación versionada</h3><div className="mt-3 flex flex-wrap gap-2">{[['complete','Dataset completo'],['e4','Sólo E4'],['crc_valid','CRC-valid'],['negatives','Negativos'],['clean','Capturas limpias'],['metadata_only','Metadatos sin IQ'],['split_manifest','Manifiesto de split']].map(([kind,label])=><a key={kind} href={api.datasetExportUrl(manifest!.dataset_id,manifest!.version,kind)} className="inline-flex items-center gap-1 rounded border border-slate-600 px-3 py-2 text-sm"><Download className="h-4 w-4"/>{label}</a>)}</div><p className="mt-2 text-xs text-slate-500">Cada exportación incluye manifest, Dataset Datasheet y checksums SHA-256. E5 nunca se asigna automáticamente.</p></section>
  {Object.keys(scientificStatus).length>0&&<section className="rounded-xl border border-sky-500/30 bg-sky-500/5 p-5"><h3 className="font-semibold">Estado científico acumulado</h3><p className="mt-1 text-xs text-slate-400">Un control negativo declarado puede superar su criterio básico aunque sus ejemplos permanezcan en cuarentena y el control reforzado siga pendiente.</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(scientificStatus).map(([key,value])=><div key={key} className="rounded border border-slate-700 p-3"><div className="text-xs text-slate-400">{scientificLabels[key]||key}</div><div className="mt-1 font-semibold">{human(value)}</div></div>)}</div></section>}
 </div>;
}
