import {useEffect,useState} from 'react';
import {BleApiService,BleCaptureCapabilities,BleCaptureJob,BleCaptureLive,BleHybridSession,BleNativeDevice,BleNativeStatus,BleScientificSummary} from '../../../app/services/bleApi';
import BleScientificResult from './BleScientificResult';
import {freezeTarget,orderTargetDevices,PRIORITY_SENSOR_TAG_ADDRESSES} from './bleTargetModel';
import {CAMPAIGN_INTENT_OPTIONS,NEGATIVE_CONTROL_OPTIONS,CampaignIntent,NegativeControlType,campaignContract,evaluateCampaignPolicy} from './campaignPolicy';
import {ensureOperation,failOperation,finishOperation,startOperation,updateOperation} from '../../../app/operations/operationTelemetry';
const api=new BleApiService(),terminal=new Set(['completed','failed','cancelled','timed_out']),activeStates=new Set(['initializing','capturing','decoding','correlating','running','pending']);
const labels:Record<string,string>={hardware:'Hardware',native_scan:'Escaneo nativo',b200_capture:'Captura B200',burst_detection:'Ráfagas',decoding:'Decodificación',correlation:'Correlación',results:'Resultados'};
const sessionStateLabel:Record<string,string>={initializing:'Inicializando',capturing:'Capturando',decoding:'Decodificando',correlating:'Correlacionando',completed:'Completada',failed:'Fallida',cancelled:'Cancelada',timed_out:'Tiempo agotado',running:'En curso',pending:'Pendiente'};
function preferredControllerSession(history:BleHybridSession[],current:BleHybridSession|null){const preferred=history.find(item=>activeStates.has(item.state))||history.find(item=>item.state==='completed')||null;if(!preferred)return current;if(!current)return preferred;if(current.state==='failed'&&preferred.session_id!==current.session_id)return preferred;return current;}
export default function BleHybridController(){
 const [native,setNative]=useState<BleNativeStatus|null>(null),[caps,setCaps]=useState<BleCaptureCapabilities|null>(null),[devices,setDevices]=useState<BleNativeDevice[]>([]),[session,setSession]=useState<BleHybridSession|null>(null),[summary,setSummary]=useState<BleScientificSummary|null>(null),[captureJob,setCaptureJob]=useState<BleCaptureJob|null>(null),[captureLive,setCaptureLive]=useState<BleCaptureLive|null>(null),[error,setError]=useState('');
 const [mode,setMode]=useState<'native'|'b200'|'hybrid'>('hybrid'),[target,setTarget]=useState('any'),[manualAddress,setManualAddress]=useState(''),[campaignIntent,setCampaignIntent]=useState<CampaignIntent|''>(''),[negativeControlType,setNegativeControlType]=useState<NegativeControlType|''>(''),[operatorConfirmation,setOperatorConfirmation]=useState(false),[channel,setChannel]=useState(37),[duration,setDuration]=useState(30),[gain,setGain]=useState(20),[refreshing,setRefreshing]=useState('');
 const [distance,setDistance]=useState(''),[orientation,setOrientation]=useState(''),[location,setLocation]=useState(''),[physicalUnit,setPhysicalUnit]=useState(''),[powerState,setPowerState]=useState(''),[referenceDevice,setReferenceDevice]=useState('');
 const refresh=(forceSdr=true)=>Promise.all([api.nativeStatus(),api.captureCapabilities(forceSdr),api.nativeDevices(),api.hybridSessions().catch(()=>[])]).then(([n,c,d,h])=>{setNative(n);setCaps(c);setDevices(d);setSession(current=>preferredControllerSession(h,current));});
 useEffect(()=>{refresh(false).catch(e=>setError(String(e)));},[]);
 useEffect(()=>{if(!session||terminal.has(session.state))return;const t=setInterval(()=>api.hybridSession(session.session_id).then(setSession),1000);return()=>clearInterval(t);},[session?.session_id,session?.state]);
 useEffect(()=>{if(!captureJob||terminal.has(captureJob.state))return;const timer=window.setInterval(async()=>{const next=await api.captureJob(captureJob.capture_id);setCaptureJob(next);setCaptureLive(await api.captureLive(next.capture_id))},500);return()=>window.clearInterval(timer)},[captureJob?.capture_id,captureJob?.state]);
 useEffect(()=>{if(captureJob){setSession(null);setSummary(null)}},[captureJob?.capture_id]);
 useEffect(()=>{if(mode==='hybrid'&&session)setCaptureJob(null)},[session?.session_id,mode]);
 useEffect(()=>{if(!captureJob)return;const id=`ble-capture:${captureJob.capture_id}`,request=captureJob.request||{},seconds=Number(request.duration_seconds||duration),rate=Number(request.sample_rate_sps||4000000),samples=captureLive?.samples_received??0,total=Math.max(1,seconds*rate);if(captureJob.state==='completed'){finishOperation(id,`${samples.toLocaleString()} muestras preservadas`);return}if(terminal.has(captureJob.state)){failOperation(id,captureJob.error||captureJob.state);return}ensureOperation({operationId:id,kind:'capturing',title:'Captura IQ B200',phase:'Preparando receptor',progressPercent:0,target:`CH${String(request.ble_channel??channel)}`,configuredDurationSeconds:seconds,estimatedTotalSeconds:seconds,detail:`${rate.toLocaleString()} S/s`});updateOperation(id,{phase:captureJob.state==='running'?'Adquiriendo muestras RF':'Preparando receptor',progressPercent:100*samples/total,processedItems:samples,totalItems:total})},[captureJob,captureLive]);
 useEffect(()=>{if(session?.state==='completed')void api.hybridScientificSummary(session.session_id).then(setSummary).catch(e=>setError(String(e)));else setSummary(null);},[session?.session_id,session?.state]);
 useEffect(()=>{if(session&&!terminal.has(session.state))ensureOperation({operationId:`ble-hybrid:${session.session_id}`,kind:'capturing',title:'Campaña BLE híbrida',phase:'Preparando hardware',progressPercent:2,target:session.target_address||'Tráfico BLE general',configuredDurationSeconds:session.duration_seconds,estimatedTotalSeconds:session.duration_seconds+60,detail:`CH${session.channel} · Windows + B200`})},[session?.session_id,session?.state]);
 useEffect(()=>{if(!session)return;const id=`ble-hybrid:${session.session_id}`,expected=Math.max(1,session.duration_seconds*4000000),samples=session.live?.telemetry?.samples_received??0,total=session.decode_progress?.total_segments??session.counters?.detected_bursts,processed=session.decode_progress?.processed_segments??session.counters?.processed_bursts??0;let percent=5,phase='Preparando hardware';if(session.state==='capturing'){percent=5+40*Math.min(1,samples/expected);phase='Capturando IQ y observaciones Windows'}else if(session.state==='decoding'){percent=55+30*(total?processed/total:0);phase='Decodificando todas las ráfagas'}else if(session.state==='correlating'){percent=90;phase='Correlacionando Windows–B200'}else if(session.state==='completed'){finishOperation(id,`${session.counters?.crc_valid_packets??0} CRC válidos · ${session.counters?.strong_matches??0} coincidencias`);return}else if(terminal.has(session.state)){failOperation(id,session.error||session.state);return}updateOperation(id,{phase,progressPercent:percent,processedItems:processed,totalItems:total,estimatedTotalSeconds:session.state==='capturing'?session.duration_seconds:null,detail:`CH${session.channel} · ${samples.toLocaleString()} muestras`})},[session]);
 const sdr=caps?.devices.find(d=>d.available),hybridActive=!!session&&!terminal.has(session.state),captureActive=!!captureJob&&!terminal.has(captureJob.state),active=hybridActive||captureActive,selected=devices.find(d=>d.device_id===target);
 const targetSelected=target!=='any'&&(target!=='manual'||!!manualAddress),seenNow=!!selected&&!!native?.scan_session_id&&selected.scan_session_id===native.scan_session_id;
 const campaignPolicy=campaignIntent?evaluateCampaignPolicy({intent:campaignIntent,targetSelected,seenNow,negativeControlType,operatorConfirmation}):{allowed:false,reason:'Seleccione el propósito científico de la campaña.'};
 const distanceHasUnit=/\d+(?:[.,]\d+)?\s*(?:mm|cm|m)\b/i.test(distance.trim());
 const metadataIssue=!distance.trim()||!orientation.trim()||!location.trim()||!physicalUnit.trim()||!powerState?'Completa distancia, orientación, ubicación, unidad física y estado de alimentación.':!distanceHasUnit?'La distancia necesita unidad física: por ejemplo 0.5 m, 50 cm o 500 mm.':'';
 const metadataReady=!metadataIssue;
 const priorityAddresses:string[]=[...PRIORITY_SENSOR_TAG_ADDRESSES];
 const targetDevices=orderTargetDevices(devices,native?.scan_session_id);
 const currentScanDevices=native?.scan_session_id?devices.filter(device=>device.scan_session_id===native.scan_session_id):[];
 const currentPriorityDevices=currentScanDevices.filter(device=>priorityAddresses.includes(device.address.toUpperCase()));
 const targetPayload=target==='any'?{kind:'any'}:target==='manual'?{kind:'device',device_id:`manual:${manualAddress.toUpperCase()}`,address:manualAddress.toUpperCase(),label:'Dirección manual',selection_source:'manual'}:selected?freezeTarget(selected,native?.scan_session_id):{kind:'any'};
 const resolveCurrentSdr=async()=>{const current=await api.captureCapabilities(true);setCaps(current);const available=current.devices.find(device=>device.available);if(!available)throw new Error('USRP B200 no disponible ahora. Comprueba USB/UHD y pulsa Actualizar hardware.');return available};
 const start=async()=>{try{setError('');if(mode==='native'){await api.startNativeScan();return refresh();}if(mode==='hybrid'&&!campaignPolicy.allowed)throw new Error(campaignPolicy.reason);if(mode==='hybrid'&&metadataIssue)throw new Error(metadataIssue);setSession(null);setSummary(null);const currentSdr=await resolveCurrentSdr();if(mode==='b200'){setCaptureLive(null);setCaptureJob(await api.createCapture({device_id:currentSdr.device_id,ble_channel:channel,center_frequency_hz:{37:2402000000,38:2426000000,39:2480000000}[channel],sample_rate_sps:4000000,bandwidth_hz:2000000,gain_mode:'manual',gain_db:gain,antenna:currentSdr.antenna_options.includes('RX2')?'RX2':currentSdr.antenna_options[0],duration_seconds:duration,sample_format:'cf32_le',purpose:'BLE dashboard capture',controlled_transmitter_state:'unknown',operator_confirmed:false,capture_role:'controlled_transmitter_active_B'}));return;}setCaptureJob(null);setCaptureLive(null);setSession(await api.startHybrid({device_id:currentSdr.device_id,channel,duration_seconds:duration,gain_db:gain,target:targetPayload,experimental_metadata:{distance,orientation,location,physical_unit_id:physicalUnit,power_state:powerState,reference_device_id:referenceDevice||null},...campaignContract(campaignIntent as CampaignIntent,negativeControlType,operatorConfirmation)}));}catch(e){const message=apiErrorMessage(e);setError(message.includes('UNKNOWN_OR_UNAVAILABLE_SDR_DEVICE')?'El backend no pudo reservar el B200. Comprueba que no exista otro proceso UHD usando el receptor y pulsa Actualizar hardware.':message.includes('404')?'El backend activo no contiene todavía el orquestador híbrido. Reinicia el backend y vuelve a intentarlo.':message);}};
 const refreshDevices=async()=>{setRefreshing('Actualizando dispositivos…');await refresh();setRefreshing(`${devices.length} dispositivos conocidos`);window.dispatchEvent(new Event('ble-native-registry-updated'));};
 const newScan=async()=>{const id=`ble-scan:${Date.now()}`,seconds=Math.max(1,duration),requestedAddress=(target==='manual'?manualAddress:selected?.address||'').toUpperCase();setError('');setSession(null);setSummary(null);setRefreshing(requestedAddress?`Buscando objetivo ${requestedAddress}...`:'Escaneando dispositivos...');startOperation({operationId:id,kind:'connecting',title:'Escaneo BLE nativo',phase:'Escuchando anuncios IoT',progressPercent:0,target:requestedAddress||'Cualquier dispositivo',configuredDurationSeconds:seconds,estimatedTotalSeconds:seconds});const timer=window.setInterval(()=>{const elapsed=Math.min(seconds,(Date.now()-Number(id.split(':')[1]))/1000);updateOperation(id,{progressPercent:100*elapsed/seconds,phase:'Escuchando anuncios IoT'})},500);try{api.nativeStatus().then(setNative).catch(()=>undefined);await api.startNativeScan();await new Promise(resolve=>setTimeout(resolve,seconds*1000));await api.stopNativeScan();const [nextNative,nextDevices,nextHistory]=await Promise.all([api.nativeStatus(),api.nativeDevices(),api.hybridSessions().catch(()=>[])]);setNative(nextNative);setDevices(nextDevices);setSession(current=>preferredControllerSession(nextHistory,current));window.dispatchEvent(new Event('ble-native-registry-updated'));const observed=requestedAddress?nextDevices.find(device=>device.address.toUpperCase()===requestedAddress&&device.scan_session_id===nextNative.scan_session_id):null;const message=requestedAddress?(observed?`Objetivo ${requestedAddress} visto ahora; ya se puede iniciar la captura positiva.`:`Objetivo ${requestedAddress} no observado en este escaneo live; no se inicia captura positiva.`):'Escaneo finalizado; registro y selector actualizados.';setRefreshing(message);finishOperation(id,message)}catch(error){const message=apiErrorMessage(error);setError(message);setRefreshing('Escaneo BLE no iniciado.');failOperation(id,message)}finally{window.clearInterval(timer)}};
 const stop=async()=>{if(mode==='native')await api.stopNativeScan();else if(captureActive&&captureJob)setCaptureJob(await api.cancelCapture(captureJob.capture_id));else if(session)setSession(await api.stopHybrid(session.session_id));refresh();};
 const persistedSamples=Number(summary?.acquisition?.captured_samples),metrics=[['Muestras',session?.live?.telemetry?.samples_received??(Number.isFinite(persistedSamples)?persistedSamples:undefined)],['Ráfagas',session?.counters?.detected_bursts],['Procesadas',session?.decode_progress?.processed_segments??session?.counters?.processed_bursts],['CRC válidos',session?.decode_progress?.crc_valid_packets??session?.counters?.crc_valid_packets],['Callbacks',session?.counters?.native_callbacks],['Coincidencias',session?.counters?.strong_matches]];
 const captureDuration=Number(captureJob?.request?.duration_seconds??duration),captureRate=Number(captureJob?.request?.sample_rate_sps??4000000),captureExpected=Math.max(1,captureDuration*captureRate),captureSamples=captureLive?.samples_received??0,capturePercent=Math.min(100,100*captureSamples/captureExpected);
 const openResults=(tab:'b200'|'hybrid'|'evidence'|'sessions')=>{if(session)window.dispatchEvent(new CustomEvent('ble-hybrid-open-results',{detail:{sessionId:session.session_id,tab}}));};
 const modeInfo={native:{title:'1. Escaneo nativo',use:'Buscar dispositivos y conectar sus sensores GATT.',hardware:'Usa sólo el adaptador Bluetooth de Windows.'},b200:{title:'2. Captura B200',use:'Guardar evidencia de radio IQ sin identificar sensores.',hardware:'Usa sólo el USRP B200; canal, duración y ganancia sí se aplican.'},hybrid:{title:'3. Captura híbrida — recomendada',use:'Buscar el dispositivo y capturar su radio al mismo tiempo para correlacionarlos.',hardware:'Necesita Bluetooth Windows y USRP B200 disponibles.'}}[mode];
 return <section className="mb-8 space-y-4"><div className="grid gap-3 md:grid-cols-2"><Card title="Adaptador BLE Windows" main={native?.available?'Disponible':'No disponible'} detail={`${native?.backend||'Comprobando'} · ${native?.scanning?'escaneando':'en espera'} · ${currentScanDevices.length} vistos en el último escaneo · ${currentPriorityDevices.length} favoritos · ${native?.device_count??0} históricos`}/><Card title="USRP B200" main={sdr?'Disponible':'No disponible'} detail={`${sdr?.label||'Sin receptor'} · ${sdr?.serial_masked||'—'} · RX2 · 4 MS/s · 2 MHz`}/></div>
 <div className="rounded-xl border border-sky-500/40 bg-sky-500/10 p-4"><div className="font-semibold text-sky-200">{modeInfo.title}</div><div className="mt-1 text-sm">{modeInfo.use}</div><div className="mt-1 text-xs text-slate-400">{modeInfo.hardware}</div>{mode==='native'&&<div className="mt-2 text-xs text-amber-300">En este modo no se usan canal ni ganancia del B200. Pulsa Iniciar para buscar dispositivos y Detener para finalizar.</div>}{mode==='hybrid'&&target==='any'&&<div className="mt-2 text-xs text-amber-300">Primero puedes usar Escaneo nativo para identificar tu SensorTag; después selecciónalo como Objetivo para una correlación específica.</div>}</div>
 <div className="rounded-xl border border-cyan-700 bg-slate-900 p-5">
  <div className="mb-3 flex flex-wrap gap-2"><button onClick={()=>void refresh()} className="rounded border px-3 py-2 text-sm">Actualizar hardware</button><button onClick={()=>void refreshDevices()} title="Recarga los dispositivos históricos; no escucha advertising nuevo." className="rounded border px-3 py-2 text-sm">Recargar historial</button><button onClick={()=>void newScan()} disabled={!!refreshing&&(refreshing.includes('Escaneando')||refreshing.includes('Buscando objetivo'))} className="rounded bg-sky-700 px-3 py-2 text-sm disabled:opacity-40">{target==='any'?'Buscar BLE ahora':'Buscar objetivo ahora'} ({Math.max(1,duration)} s)</button>{refreshing&&<span className="self-center text-sm text-sky-300">{refreshing}</span>}</div>
  <div className="mb-4 flex flex-wrap gap-2">{([['native','Escaneo nativo'],['b200','Captura B200'],['hybrid','Captura híbrida · recomendada']] as const).map(x=><button key={x[0]} onClick={()=>setMode(x[0])} className={`rounded px-3 py-2 ${mode===x[0]?'bg-cyan-600':'bg-slate-800'}`}>{x[1]}</button>)}</div>
  {mode==='hybrid'&&<div className="mb-4 rounded-lg border border-violet-500/40 bg-violet-500/10 p-4"><div className="font-semibold text-violet-200">Propósito científico obligatorio</div><div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="Propósito de la campaña"><select value={campaignIntent} onChange={e=>{setCampaignIntent(e.target.value as CampaignIntent|'');setOperatorConfirmation(false);setNegativeControlType('')}} className="w-full rounded bg-slate-800 p-2"><option value="">Seleccione antes de iniciar…</option>{CAMPAIGN_INTENT_OPTIONS.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></Field>{campaignIntent&&<div className="rounded border border-slate-700 p-3 text-sm text-slate-300">{CAMPAIGN_INTENT_OPTIONS.find(option=>option.value===campaignIntent)?.description}</div>}</div>{campaignIntent==='negative_control'&&<div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="Condición negativa declarada"><select value={negativeControlType} onChange={e=>{setNegativeControlType(e.target.value as NegativeControlType|'');setOperatorConfirmation(false)}} className="w-full rounded bg-slate-800 p-2"><option value="">Seleccione la condición…</option>{NEGATIVE_CONTROL_OPTIONS.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></Field><label className="flex items-center gap-2 rounded border border-amber-500/40 p-3 text-sm"><input type="checkbox" checked={operatorConfirmation} onChange={e=>setOperatorConfirmation(e.target.checked)}/>Confirmo que verifiqué físicamente esta condición antes de capturar.</label></div>}<p className={`mt-3 text-sm ${campaignPolicy.allowed?'text-sky-300':'text-amber-300'}`}>{campaignPolicy.reason||'Contrato experimental completo.'}</p></div>}
  {mode==='hybrid'&&<div className="mb-4 rounded-lg border border-slate-700 p-4"><div className="font-semibold">Metadatos experimentales obligatorios</div><p className="mt-1 text-xs text-slate-400">La fecha y hora se registran automáticamente. El dispositivo de referencia es opcional cuando no corresponde.</p><div className="mt-3 grid gap-3 md:grid-cols-3"><Field label="Distancia con unidad"><input value={distance} onChange={e=>setDistance(e.target.value)} placeholder="0,50 m" className="w-full rounded bg-slate-800 p-2"/></Field><Field label="Orientación"><input value={orientation} onChange={e=>setOrientation(e.target.value)} placeholder="frontal, 0°" className="w-full rounded bg-slate-800 p-2"/></Field><Field label="Ubicación"><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="laboratorio BLE, posición A" className="w-full rounded bg-slate-800 p-2"/></Field><Field label="Unidad física"><input value={physicalUnit} onChange={e=>setPhysicalUnit(e.target.value)} placeholder="CC2650-UNIT-01" className="w-full rounded bg-slate-800 p-2"/></Field><Field label="Estado de alimentación"><select value={powerState} onChange={e=>setPowerState(e.target.value)} className="w-full rounded bg-slate-800 p-2"><option value="">Seleccione…</option><option value="powered_on">Objetivo encendido</option><option value="powered_off">Objetivo apagado</option><option value="physically_absent">Objetivo ausente</option></select></Field><Field label="Dispositivo de referencia, si corresponde"><input value={referenceDevice} onChange={e=>setReferenceDevice(e.target.value)} placeholder="Opcional" className="w-full rounded bg-slate-800 p-2"/></Field></div>{metadataIssue&&<p className="mt-3 text-sm text-amber-300">{metadataIssue}</p>}</div>}
  <div className="grid gap-3 md:grid-cols-5"><Field label="Objetivo"><select value={target} onChange={e=>setTarget(e.target.value)} className="w-full bg-slate-800 p-2"><option value="any">Cualquier dispositivo BLE</option><optgroup label="Objetivos prioritarios">{targetDevices.filter(d=>priorityAddresses.includes(d.address.toUpperCase())).map(d=><option value={d.device_id} key={d.device_id}>{d.profile_label||d.local_name||'SensorTag'} · {d.address} · {d.scan_session_id===native?.scan_session_id?'visto ahora':'histórico'}</option>)}</optgroup><optgroup label="Registro nativo BLE">{targetDevices.filter(d=>!priorityAddresses.includes(d.address.toUpperCase())).map(d=><option value={d.device_id} key={d.device_id}>{d.local_name||d.profile_label||'BLE'} · {d.address} · {d.rssi_dbm??'—'} dBm · {d.connection}</option>)}</optgroup><option value="manual">Introducir dirección manualmente</option></select>{target==='manual'&&<input value={manualAddress} onChange={e=>setManualAddress(e.target.value)} placeholder="AA:BB:CC:DD:EE:FF" className="mt-2 w-full bg-slate-800 p-2"/>}</Field><Field label="Canal"><select value={channel} onChange={e=>setChannel(+e.target.value)} className="w-full bg-slate-800 p-2">{[37,38,39].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Duración (s)"><input type="number" min="1" max="60" value={duration} onChange={e=>setDuration(+e.target.value)} className="w-full bg-slate-800 p-2"/></Field><Field label="Ganancia dB"><input type="number" value={gain} onChange={e=>setGain(+e.target.value)} className="w-full bg-slate-800 p-2"/></Field><div className="flex items-end gap-2"><button onClick={start} disabled={active||(!sdr&&mode!=='native')||(target==='manual'&&!manualAddress)||(mode==='hybrid'&&(!campaignPolicy.allowed||!metadataReady))} className="rounded bg-emerald-600 px-4 py-2 disabled:opacity-40">Iniciar</button><button onClick={stop} disabled={!active&&!(mode==='native'&&native?.scanning)} className="rounded bg-rose-700 px-4 py-2 disabled:opacity-40">Detener</button></div></div>
  {selected&&!seenNow&&target!=='any'&&campaignIntent==='exploratory_target_search'&&<p className="mt-3 text-sm text-amber-300">Búsqueda exploratoria de un objetivo histórico. Puede continuar, pero esta ejecución no se etiquetará como prueba positiva ni como control negativo.</p>}{error&&<p className="mt-3 text-rose-400">{error}</p>}
 </div>
 {captureJob&&<CaptureLivePanel job={captureJob} live={captureLive} channel={channel} duration={captureDuration} rate={captureRate} expected={captureExpected} samples={captureSamples} percent={capturePercent}/>} 
 {session&&<div className="rounded-xl border border-slate-700 bg-slate-900 p-5"><div className="flex justify-between"><div><div className="text-xs text-slate-400">SESIÓN {session.session_id}</div><div className="text-xl">{sessionStateLabel[session.state]||session.state}</div></div><div>CH{session.channel} · {session.duration_seconds}s</div></div><div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-7">{Object.entries(labels).map(([k,v])=><div key={k} className={`rounded border p-2 text-center text-xs ${session.steps?.[k]==='completed'?'border-emerald-600 text-emerald-300':session.steps?.[k]==='running'?'border-cyan-500 text-cyan-300':'border-slate-700 text-slate-500'}`}>{v}<div>{sessionStateLabel[session.steps?.[k]||'pending']||session.steps?.[k]||'Pendiente'}</div></div>)}</div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-6">{metrics.map(([l,v])=><Card key={String(l)} title={String(l)} main={typeof v==='number'?String(v):'—'} detail=""/>)}</div>{session.error&&<p className="mt-3 text-rose-400">{session.error}</p>}</div>}
 {summary&&<BleScientificResult summary={summary}/>} 
 {session?.state==='completed'&&<div className="rounded-xl border border-emerald-500/40 bg-emerald-500/10 p-4"><div className="font-semibold text-emerald-200">Resultados de esta sesión listos</div><div className="mt-1 text-sm text-slate-300">Abre los datos de {session.session_id}; estas vistas no mezclan sesiones anteriores.</div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>openResults('b200')} className="rounded bg-sky-600 px-3 py-2 text-sm">Ver {session.counters?.crc_valid_packets??0} paquetes</button><button onClick={()=>openResults('hybrid')} className="rounded bg-emerald-600 px-3 py-2 text-sm">Ver {session.counters?.strong_matches??0} coincidencias</button><button onClick={()=>openResults('evidence')} className="rounded bg-slate-700 px-3 py-2 text-sm">Ver evidencia</button><button onClick={()=>openResults('sessions')} className="rounded bg-slate-700 px-3 py-2 text-sm">Ver sesiones</button></div></div>}
 {session&&<div className="grid gap-3 md:grid-cols-4"><Card title="Objetivo de la sesión" main={session.target_name_at_start||'Objetivo histórico'} detail={session.target_address||'Sin dirección congelada'}/><Card title="Propósito" main={CAMPAIGN_INTENT_OPTIONS.find(x=>x.value===String(session.campaign_intent||'').toLowerCase())?.label||session.campaign_intent||'Histórico no declarado'} detail="Leído del manifiesto de la sesión"/><Card title="Condición" main={NEGATIVE_CONTROL_OPTIONS.find(x=>x.value===String(session.negative_control_type||'').toLowerCase())?.label||'No aplica'} detail="No depende del selector actual"/><Card title="Resultado" main={session.negative_control_result||summary?.general_result||sessionStateLabel[session.state]||session.state} detail={`Sesión ${session.session_id}`}/></div>}</section>;
}
function CaptureLivePanel({job,live,channel,duration,rate,expected,samples,percent}:{job:BleCaptureJob;live:BleCaptureLive|null;channel:number;duration:number;rate:number;expected:number;samples:number;percent:number}){return <div className="rounded-xl border border-cyan-500/50 bg-slate-900 p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="text-xs font-semibold text-cyan-300">CAPTURA ACTUAL · TELEMETRÍA EN TIEMPO REAL</div><div className="font-mono text-lg">{job.capture_id}</div><div className="text-sm text-slate-400">{job.state==='running'?'El B200 está recibiendo muestras ahora.':`Estado: ${job.state}`}</div></div><div>CH{String(job.request?.ble_channel??channel)} · {duration}s · {rate.toLocaleString()} S/s</div></div><div className="mt-4"><div className="flex justify-between text-sm"><span>{job.state==='running'?'Adquiriendo IQ':'Captura'}</span><b>{percent.toFixed(1)}%</b></div><div className="mt-2 h-3 overflow-hidden rounded bg-slate-800"><div className="h-full bg-cyan-500 transition-all" style={{width:`${percent}%`}}/></div></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-6"><Card title="Muestras recibidas" main={samples.toLocaleString()} detail={`de ${expected.toLocaleString()}`}/><Card title="Bytes escritos" main={(live?.bytes_written??0).toLocaleString()} detail="archivo IQ"/><Card title="Overflows" main={String(live?.stream_overflows??0)} detail="pérdidas notificadas"/><Card title="Discontinuidades" main={String(live?.input_discontinuities??0)} detail="flujo IQ"/><Card title="Potencia media" main={live?.average_power_dbfs==null?'—':`${live.average_power_dbfs.toFixed(1)} dBFS`} detail="live"/><Card title="Clipping" main={live?.clipping_percentage==null?'—':`${live.clipping_percentage.toFixed(3)}%`} detail="live"/></div>{job.error&&<p className="mt-3 text-rose-400">{job.error}</p>}</div>}
function Card({title,main,detail}:{title:string;main:string;detail:string}){return <div className="rounded-xl border border-slate-700 bg-slate-900 p-4"><div className="text-xs uppercase text-slate-400">{title}</div><div className="mt-1 text-lg">{main}</div><div className="text-sm text-slate-400">{detail}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm">{label}<div className="mt-1">{children}</div></label>}
function apiErrorMessage(error:unknown){const response=(error as {response?:{data?:unknown;status?:number}})?.response,detail=(response?.data as {detail?:unknown})?.detail;if(typeof detail==='string')return detail;if(detail)return JSON.stringify(detail);return error instanceof Error?error.message:String(error)}
