import {BleScientificSummary} from '../../../app/services/bleApi';

const labels:Record<string,string>={iq_samples:'Muestras IQ',candidate_bursts:'Ráfagas candidatas',processed_bursts:'Ráfagas procesadas',processing_coverage_percent:'Cobertura de procesamiento',crc_valid_packets:'Paquetes CRC válidos',crc_yield_percent:'Rendimiento CRC',eligible_advertisements:'Advertisements elegibles',strong_matches:'Coincidencias fuertes',unique_correlated_devices:'Dispositivos únicos correlacionados'};
const intentLabels:Record<string,string>={positive_target_validation:'Validación positiva del objetivo',negative_control:'Control negativo',exploratory_target_search:'Búsqueda exploratoria'};
const statusLabels:Record<string,string>={COMPLETED:'Completada',COMPLETED_WITH_LOSS:'Completada con pérdidas',PASSED:'Superada',PASSED_SINGLE_RUN:'Superado en una ejecución',PASSED_TO_E2:'Superada hasta E2',DEMONSTRATED:'Demostrada',NOT_DEMONSTRATED:'No demostrada',NEGATIVE_CONTROL_PASSED:'Control negativo superado',NEGATIVE_CONTROL_PASSED_SINGLE_RUN:'Control negativo superado en una ejecución',PENDING:'Pendiente',FAILED:'Fallido',FAILED_FALSE_ATTRIBUTION:'Fallido: atribución falsa',SUITABLE:'Apto',NOT_SUITABLE:'No apto'};
const value=(item:unknown)=>item==null?'No disponible':typeof item==='boolean'?(item?'Sí':'No'):String(item);
const Field=({name,data}:{name:string;data:unknown})=><div className="rounded border border-slate-700 p-3"><div className="text-xs text-slate-400">{name}</div><div className="font-semibold">{value(data)}</div></div>;

export default function BleScientificResult({summary}:{summary:BleScientificSummary}){
 const targetStatus=String(summary.target.status||'TARGET_NOT_EVALUATED');
 const interpretation=(summary.target.interpretation||{}) as {meaning?:string;does_not_mean?:string[];possible_causes?:string[]};
 const campaignIntent=String(summary.campaign?.campaign_intent||'exploratory_target_search');
 const conclusion=String(summary.conclusion?.statement||'No hay conclusión estructurada disponible.');
 const validations=summary.functional_validation||{};
 const negative=summary.negative_control;
 return <div className="space-y-4 rounded-xl border border-emerald-500/40 bg-slate-950 p-5">
  <div className="text-xs font-bold tracking-[.2em] text-emerald-300">RESULTADO CIENTÍFICO</div>
  <div className="grid gap-3 md:grid-cols-2"><Field name="Propósito declarado" data={intentLabels[campaignIntent]||campaignIntent}/><Field name="Nivel máximo de evidencia RF" data={summary.evidence_level}/></div>
  {negative&&<div className="rounded border border-violet-500/50 bg-violet-500/10 p-4"><div className="font-semibold text-violet-200">Resultado del control negativo</div><div className="mt-1 text-xs text-slate-300">E0–E5 mide evidencia positiva recuperada; el control negativo mide si se evitó atribuir incorrectamente tráfico al objetivo.</div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Field name="Condición declarada" data={negative.declared_condition_display}/><Field name="Confirmación del operador" data={negative.operator_confirmation}/><Field name="Tráfico ambiental BLE recuperado" data={negative.ambient_ble_traffic_recovered}/><Field name="Paquetes CRC válidos ambientales" data={negative.ambient_crc_valid_packets}/><Field name="Observaciones Windows del objetivo" data={negative.target_native_observations}/><Field name="Paquetes B200 del objetivo" data={negative.target_b200_crc_valid_packets}/><Field name="Coincidencias del objetivo" data={negative.target_strong_matches}/><Field name="Atribuciones falsas al objetivo" data={negative.false_target_attributions}/><Field name="Control negativo básico" data={statusLabels[negative.basic_control]||negative.basic_control}/><Field name="Correlador con referencia positiva" data={statusLabels[negative.positive_reference_correlation]||negative.positive_reference_correlation}/><Field name="Control negativo reforzado" data={statusLabels[negative.reinforced_control]||negative.reinforced_control}/><Field name="Resultado" data={statusLabels[negative.result]||negative.result}/></div><p className="mt-3 text-xs text-amber-200">{negative.condition_provenance}</p></div>}
  {negative&&<div className="rounded border border-emerald-500/40 bg-emerald-500/10 p-4"><div className="font-semibold text-emerald-200">Conclusión del control negativo</div><p className="mt-2 text-sm leading-6">{conclusion}</p></div>}
  <div><div className="text-xs text-slate-400">Pregunta</div><div className="text-lg">{summary.question}</div></div>
  <div className="grid gap-3 md:grid-cols-3"><Field name="Recepción y decoding BLE" data={Number(summary.funnel.crc_valid_packets)>0?`DEMOSTRADOS — nivel ${summary.evidence_level}`:'NO DEMOSTRADOS'}/><Field name="Correlación entre receptores" data={Number(summary.funnel.strong_matches)>0?'DEMOSTRADA':'NO DEMOSTRADA'}/><Field name="Dispositivo objetivo" data={targetStatus==='TARGET_NOT_OBSERVED'?'NO OBSERVADO':targetStatus}/></div>
  <div><div className="mb-2 font-semibold">Embudo de evidencia</div><div className="grid grid-cols-2 gap-2 lg:grid-cols-7">{Object.entries(summary.funnel).map(([key,item])=><Field key={key} name={labels[key]||key.replaceAll('_',' ')} data={`${value(item)}${key.includes('percent')?' %':''}`}/>)}</div></div>
  <div className="rounded border border-slate-700 p-4"><div className="font-semibold">Validaciones funcionales separadas</div><div className="mt-3 grid gap-2 md:grid-cols-2 lg:grid-cols-3">{Object.entries(validations).map(([key,item])=><div key={key} className="rounded border border-slate-700 p-3"><div className="text-sm font-semibold">{item.label}</div><div className={`mt-1 text-sm ${item.status.includes('NOT_')||item.status.includes('LOSS')?'text-amber-300':'text-emerald-300'}`}>{statusLabels[item.status]||item.status}</div><div className="mt-1 text-xs text-slate-400">{item.detail}</div></div>)}</div></div>
  <div className="grid gap-3 lg:grid-cols-2"><div className="rounded border border-slate-700 p-4"><div className="font-semibold">Resultado del dispositivo objetivo</div><div className="mt-2 grid grid-cols-2 gap-2"><Field name="Nombre congelado" data={summary.target.name}/><Field name="Dirección" data={summary.target.address}/><Field name="Visto por Windows" data={summary.target.seen_by_windows}/><Field name="Callbacks del objetivo" data={summary.target.windows_callbacks}/><Field name="Visto por B200" data={summary.target.seen_by_b200}/><Field name="Paquetes CRC del objetivo" data={summary.target.b200_crc_packets}/><Field name="Coincidencias fuertes" data={summary.target.strong_matches}/><Field name="Resultado" data={targetStatus}/></div>{targetStatus==='TARGET_NOT_OBSERVED'&&<details className="mt-3 rounded border border-amber-500/40 p-3 text-sm"><summary className="cursor-pointer font-semibold text-amber-300">Qué significa TARGET_NOT_OBSERVED</summary><p className="mt-2">{interpretation.meaning}</p><div className="mt-2 text-xs text-slate-300"><b>No significa:</b> {(interpretation.does_not_mean||[]).join(' ')}</div><div className="mt-2 text-xs text-slate-400"><b>Posibles causas:</b> {(interpretation.possible_causes||[]).join(' · ')}</div></details>}</div><div className="rounded border border-slate-700 p-4"><div className="font-semibold">Conclusión respaldada</div><p className="mt-2 text-sm leading-6">{conclusion}</p><div className="mt-3 text-sm font-semibold text-amber-300">No demostrado por esta sesión</div><ul className="mt-1 list-disc pl-5 text-sm text-slate-300">{summary.limitations.map(item=><li key={item}>{item}</li>)}</ul></div></div>
  <div className="grid gap-3 lg:grid-cols-3"><Quality title="Calidad de adquisición" data={summary.acquisition}/><Quality title="Calidad del decoder" data={summary.decoder}/><Quality title="Calidad de correlación" data={summary.correlation}/></div>
  <div><div className="mb-2 font-semibold">Evidencia verificable</div><div className="grid gap-2 md:grid-cols-2 lg:grid-cols-3">{Object.entries(summary.artifacts).map(([name,item])=>{const empty=item.available&&item.record_count===0;return <details key={name} className="rounded border border-slate-700 p-3"><summary className="cursor-pointer font-semibold">{name.replaceAll('_',' ')} · {item.available?(empty?'integridad verificada · 0 registros':'integridad verificada'):'no disponible'}</summary>{item.available&&<div className="mt-2 space-y-1 text-xs text-slate-400"><div>{item.name}</div>{item.record_count!=null&&<div>Registros: {item.record_count}</div>}{empty&&<div className="font-semibold text-amber-300">No se produjeron coincidencias</div>}<div>{item.size_bytes?.toLocaleString()} bytes</div><div className="break-all">SHA-256: {item.sha256}</div><div>{item.created_at_utc}</div><div className="break-all">Ruta: {item.path}</div></div>}</details>})}</div></div>
  <p className="text-xs text-slate-400">Un CRC válido demuestra coherencia binaria del paquete reconstruido; no demuestra identidad física ni cobertura completa. Los paquetes B200-only conservan relación UNKNOWN, salvo un control negativo predeclarado que permite `NEGATIVE_BY_EXPERIMENTAL_CONTRACT` únicamente respecto al objetivo y sin identificar al transmisor ambiental.</p>
 </div>;
}

function Quality({title,data}:{title:string;data:Record<string,unknown>}){return <div className="rounded border border-slate-700 p-4"><div className="mb-2 font-semibold">{title}</div><div className="grid grid-cols-2 gap-2">{Object.entries(data).map(([key,item])=><Field key={key} name={key.replaceAll('_',' ')} data={item}/>)}</div></div>}
