import {useEffect,useMemo,useState} from 'react';
import {BleApiService,BleHybridSession,BleNativeDevice,BleScientificSummary} from '../../../app/services/bleApi';
import {CAMPAIGN_INTENT_OPTIONS,NEGATIVE_CONTROL_OPTIONS,CampaignIntent,NegativeControlType,campaignContract,evaluateCampaignPolicy} from './campaignPolicy';

const api=new BleApiService();
const priorities=['BC:6A:29:AB:DE:13','B0:B4:48:C0:36:06'];
const terminal=new Set(['completed','failed','cancelled','timed_out']);

export default function BleUc02Panel(){
 const [devices,setDevices]=useState<BleNativeDevice[]>([]),[scanId,setScanId]=useState<string|null>(null),[targetId,setTargetId]=useState(''),[channel,setChannel]=useState(37),[duration,setDuration]=useState(30),[scanning,setScanning]=useState(false),[message,setMessage]=useState(''),[campaign,setCampaign]=useState<BleHybridSession|null>(null),[summary,setSummary]=useState<BleScientificSummary|null>(null);
 const [intent,setIntent]=useState<CampaignIntent|''>(''),[negativeType,setNegativeType]=useState<NegativeControlType|''>(''),[confirmed,setConfirmed]=useState(false);
 const refresh=async()=>{const [list,status,sessions]=await Promise.all([api.nativeDevices(),api.nativeStatus(),api.hybridSessions()]);setDevices(list);setScanId(status.scan_session_id||null);const latest=sessions.find(item=>item.state==='completed'&&item.target_mode==='specific_device'&&priorities.includes((item.target_address||'').toUpperCase()));const preferred=targetId?list.find(d=>d.device_id===targetId):priorities.map(address=>list.find(d=>d.address.toUpperCase()===address)).find(Boolean);if(preferred)setTargetId(preferred.device_id);if(latest&&!campaign){setCampaign(latest);setSummary(await api.hybridScientificSummary(latest.session_id));const matching=list.find(d=>d.address.toUpperCase()===(latest.target_address||'').toUpperCase());if(matching)setTargetId(matching.device_id)}};
 useEffect(()=>{void refresh()},[]);
 useEffect(()=>{if(!campaign||terminal.has(campaign.state))return;const timer=setInterval(async()=>{const next=await api.hybridSession(campaign.session_id);setCampaign(next);if(next.state==='completed')setSummary(await api.hybridScientificSummary(next.session_id))},1000);return()=>clearInterval(timer)},[campaign?.session_id,campaign?.state]);
 const priorityDevices=useMemo(()=>priorities.map(address=>devices.find(device=>device.address.toUpperCase()===address)).filter((item):item is BleNativeDevice=>!!item),[devices]);
 const target=devices.find(device=>device.device_id===targetId),seenNow=!!target&&!!scanId&&target.scan_session_id===scanId;
 const policy=intent?evaluateCampaignPolicy({intent,targetSelected:!!target,seenNow,negativeControlType:negativeType,operatorConfirmation:confirmed}):{allowed:false,reason:'Seleccione el propósito científico de la campaña.'};
 const scan=async()=>{setScanning(true);setMessage('Escaneando durante 30 segundos…');try{const started=await api.startNativeScan() as {scan_session_id?:string};setScanId(started.scan_session_id||null);await new Promise(resolve=>setTimeout(resolve,30000));await api.stopNativeScan();await refresh();window.dispatchEvent(new Event('ble-native-registry-updated'));setMessage('Escaneo finalizado. El estado Visto ahora ya está actualizado.')}finally{setScanning(false)}};
 const start=async()=>{if(!target||!intent||!policy.allowed){setMessage(policy.reason);return}const caps=await api.captureCapabilities(true),sdr=caps.devices.find(d=>d.available);if(!sdr){setMessage('USRP B200 no disponible.');return}setSummary(null);setCampaign(await api.startHybrid({device_id:sdr.device_id,channel,duration_seconds:duration,gain_db:20,target:{kind:'device',device_id:target.device_id,address:target.address,label:target.local_name||target.profile_label||'SensorTag',selection_source:seenNow?'uc02_current_native_scan':'native_registry_history'},...campaignContract(intent,negativeType,confirmed)}))};
 const stages=['crear sesión','scan Windows','captura IQ B200','detectar ráfagas','procesar todas las ráfagas','validar CRC','correlacionar','resultado científico'];
 return <div className="space-y-4">
  <div className="rounded-xl border border-sky-500/40 bg-slate-900 p-5"><div className="text-xs font-bold tracking-[.2em] text-sky-300">BLE-UC-02</div><h2 className="mt-1 text-xl font-semibold">Identificación híbrida de un SensorTag</h2><p className="mt-2 text-sm text-slate-300">Controlador y UC-02 aplican el mismo contrato para validación positiva, control negativo y búsqueda exploratoria.</p></div>
  <div className="grid gap-3 md:grid-cols-2">{priorityDevices.map(device=>{const current=!!scanId&&device.scan_session_id===scanId;return <button key={device.device_id} onClick={()=>setTargetId(device.device_id)} className={`rounded-xl border p-4 text-left ${targetId===device.device_id?'border-sky-400 bg-sky-500/10':'border-slate-700'}`}><div className="font-semibold">{device.profile_label||device.local_name||'SensorTag'}</div><div className="font-mono text-sm">{device.address}</div><div className={`mt-2 text-sm ${current?'text-emerald-300':'text-amber-300'}`}>{current?'Visto ahora':'Histórico — no observado actualmente'}</div><div className="text-xs text-slate-400">Última observación: {new Date(device.last_seen_utc).toLocaleString()} · RSSI {device.rssi_dbm??'—'} dBm · GATT {device.connection}</div></button>})}</div>
  <div className="rounded-xl border border-violet-500/40 bg-violet-500/10 p-5"><div className="font-semibold">Propósito científico obligatorio</div><select value={intent} onChange={e=>{setIntent(e.target.value as CampaignIntent|'');setNegativeType('');setConfirmed(false)}} className="mt-3 w-full rounded bg-slate-800 p-2"><option value="">Seleccione antes de iniciar…</option>{CAMPAIGN_INTENT_OPTIONS.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>{intent==='negative_control'&&<div className="mt-3 grid gap-3 md:grid-cols-2"><select value={negativeType} onChange={e=>{setNegativeType(e.target.value as NegativeControlType|'');setConfirmed(false)}} className="rounded bg-slate-800 p-2"><option value="">Declare la condición negativa…</option>{NEGATIVE_CONTROL_OPTIONS.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select><label className="flex items-center gap-2 rounded border border-amber-500/40 p-3 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo la condición física antes de capturar.</label></div>}<p className={`mt-3 text-sm ${policy.allowed?'text-sky-300':'text-amber-300'}`}>{policy.reason||'Contrato experimental completo.'}</p></div>
  <div className="rounded-xl border border-slate-700 p-5"><div className="flex flex-wrap items-end gap-3"><button disabled={scanning} onClick={()=>void scan()} className="rounded bg-sky-700 px-4 py-2 disabled:opacity-40">{scanning?'Escaneando…':'1. Nuevo escaneo nativo'}</button><label className="text-sm">Canal<select value={channel} onChange={e=>setChannel(+e.target.value)} className="ml-2 rounded bg-slate-800 p-2">{[37,38,39].map(item=><option key={item}>{item}</option>)}</select></label><label className="text-sm">Duración<input type="number" min="10" max="60" value={duration} onChange={e=>setDuration(+e.target.value)} className="ml-2 w-20 rounded bg-slate-800 p-2"/> s</label><button disabled={!policy.allowed||!!campaign&&!terminal.has(campaign.state)} onClick={()=>void start()} className="rounded bg-emerald-700 px-4 py-2 disabled:opacity-40">2. Iniciar captura híbrida</button></div>{message&&<p className="mt-3 text-sm text-sky-300">{message}</p>}</div>
  {campaign&&<div className="rounded-xl border border-slate-700 p-5"><div className="font-semibold">Sesión {campaign.session_id} · {campaign.state}</div><div className="text-xs text-violet-300">Propósito: {campaign.campaign_intent||'exploratory_target_search (heredado)'}</div><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4">{stages.map((stage,index)=><div key={stage} className={`rounded border p-2 text-xs ${Object.values(campaign.steps||{})[index]==='completed'?'border-emerald-600 text-emerald-300':'border-slate-700'}`}>{index+1}. {stage}</div>)}</div></div>}
  {summary&&<div className="rounded-xl border border-emerald-500/40 p-5"><div className="text-lg font-semibold">Resultado del objetivo: {String(summary.target.status)}</div><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4"><Metric label="Windows" value={summary.target.seen_by_windows}/><Metric label="Callbacks objetivo" value={summary.target.windows_callbacks}/><Metric label="B200" value={summary.target.seen_by_b200}/><Metric label="CRC objetivo" value={summary.target.b200_crc_packets}/><Metric label="Coincidencias fuertes" value={summary.target.strong_matches}/><Metric label="Mejor |Δt|" value={summary.target.best_delta_ms==null?'—':`${summary.target.best_delta_ms} ms`}/><Metric label="Canal" value={summary.acquisition.channel}/><Metric label="Nivel" value={summary.evidence_level}/><Metric label="Resultado general" value={summary.general_result}/></div><div className="mt-3 flex gap-2"><button onClick={()=>window.dispatchEvent(new CustomEvent('ble-hybrid-open-results',{detail:{sessionId:summary.session_id,tab:'hybrid'}}))} className="rounded bg-emerald-700 px-3 py-2 text-sm">Abrir coincidencias</button><button onClick={()=>window.dispatchEvent(new CustomEvent('ble-hybrid-open-results',{detail:{sessionId:summary.session_id,tab:'evidence'}}))} className="rounded bg-slate-700 px-3 py-2 text-sm">Abrir evidencia</button></div></div>}
  {target&&<div className="rounded-xl border border-slate-700 p-5"><div className="font-semibold">Evidencia GATT complementaria</div><div className="mt-2 text-sm">Identificación OTA: {String(summary?.target.status||'pendiente')} · Estado GATT: {target.connection} · Perfil: {target.profile_label||'sin clasificar'} · Registros de medición válidos: {target.measurements?.filter(m=>m.value!=null).length??0} · Magnitudes: {new Set(target.measurements?.filter(m=>m.value!=null).map(m=>m.measurement_type)).size} · Sensores activos: {[target.environmental_sensor,target.ir_temperature_sensor].filter(sensor=>sensor?.active).length} · RAW_ONLY: {target.measurements?.filter(m=>m.value==null).length??0}</div><p className="mt-2 text-xs text-slate-400">GATT describe la identidad lógica y capacidades; no sustituye una coincidencia B200.</p></div>}
 </div>;
}

function Metric({label,value}:{label:string;value:unknown}){return <div className="rounded border border-slate-700 p-3"><div className="text-xs text-slate-400">{label}</div><b>{typeof value==='boolean'?(value?'Sí':'No'):String(value??'—')}</b></div>}
