import {useAppStore} from '../store/AppStore';
export type OperationProgress={operationId:string;kind:'connecting'|'capturing'|'streaming'|'processing';title:string;detail?:string;phase:string;progressPercent?:number;target?:string;configuredDurationSeconds?:number;processedItems?:number;totalItems?:number;startedAtMs:number;estimatedTotalSeconds?:number|null};
const active=new Map<string,OperationProgress>(),timers=new Map<string,number>();
const publish=(op:OperationProgress)=>{const elapsed=Math.max(0,(Date.now()-op.startedAtMs)/1000),progress=op.progressPercent==null?undefined:Math.max(0,Math.min(100,Math.round(op.progressPercent))),remaining=op.estimatedTotalSeconds==null?null:Math.max(0,op.estimatedTotalSeconds-elapsed);useAppStore.getState().setGlobalActivity({visible:true,...op,progressPercent:progress,elapsedSeconds:Math.round(elapsed),estimatedRemainingSeconds:remaining==null?null:Math.round(remaining)});};
export const startOperation=(op:Omit<OperationProgress,'startedAtMs'|'phase'> & {phase?:string})=>{const value={...op,phase:op.phase||'Iniciando',startedAtMs:Date.now()};active.set(value.operationId,value);publish(value);timers.set(value.operationId,window.setInterval(()=>{const current=active.get(value.operationId);if(current)publish(current)},1000));return value.operationId;};
export const ensureOperation=(op:Omit<OperationProgress,'startedAtMs'|'phase'> & {phase?:string})=>active.has(op.operationId)?op.operationId:startOperation(op);
export const updateOperation=(id:string,updates:Partial<Omit<OperationProgress,'operationId'|'startedAtMs'>>)=>{const current=active.get(id);if(current){const next={...current,...updates};active.set(id,next);publish(next)}};
export const finishOperation=(id:string,detail='Completado')=>{const current=active.get(id);if(current)publish({...current,phase:'Completado',detail,progressPercent:100});active.delete(id);const timer=timers.get(id);if(timer)window.clearInterval(timer);timers.delete(id);window.setTimeout(()=>{if(!active.size)useAppStore.getState().clearGlobalActivity()},2500)};
export const failOperation=(id:string,detail:string)=>{const current=active.get(id);if(current)publish({...current,phase:'Error',detail});active.delete(id);const timer=timers.get(id);if(timer)window.clearInterval(timer);timers.delete(id)};
