"""The initial, hand-verified RF model catalog (spec section 7).

Every entry below was independently checked against its real source (the
Hugging Face model card or GitHub repository itself) before being written
here -- via a live fetch, not from memory. Where that check could not
confirm a detail, the field is left `None`/`UNKNOWN` rather than guessed,
and `independently_verified=False` is set with a `notes` explanation for
the one entry (INRIA RFFI) this session could not locate a working source
URL for at all.

This is a SEED, not the whole catalog -- see huggingface_provider.py for
the one live discovery source implemented so far (spec section 13). GitHub
code search, Zenodo, arXiv, Papers with Code, and Kaggle (spec sections
14-15) are real, disclosed gaps: not built in this pass, not silently
faked as "coming soon" buttons that go nowhere.
"""

from __future__ import annotations

from app.modules.ai_research_plugin.catalog.contracts import (
    CatalogEntryKind,
    CatalogInputRepresentation,
    CatalogOriginalFormat,
    CatalogStatus,
    CatalogTask,
    RFModelCatalogEntry,
)

_SIGIDWIKI_CLASSES = [
    "4G LTE", "5G NR downlink", "ACARS", "AM", "AIS", "ALIS", "APT", "Bluetooth",
    "DGPS", "DAB+", "DMR", "DVB-T", "HFDL", "Instrument Landing System",
    "M20 Radiosonde", "Morse/CW", "NDB", "Radar altimeter", "STANAG 5065",
    "Secondary Surveillance Radar", "SSB Voice", "Tetrapol", "VDL Mode 2", "VOR",
]


def curated_catalog_entries() -> list[RFModelCatalogEntry]:
    return [
        RFModelCatalogEntry(
            id="CATALOG-ATDI-AST-SIGIDWIKI",
            name="ATDI AST — SIGIDwiki",
            kind=CatalogEntryKind.MODEL,
            provider="ATDI-Group (Hugging Face)",
            source_url="https://huggingface.co/ATDI-Group/AST_finetuned_SIGIDwiki",
            download_url="https://huggingface.co/ATDI-Group/AST_finetuned_SIGIDwiki/tree/main",
            task=CatalogTask.RADIO_SYSTEM_IDENTIFICATION,
            signal_domain="Broad radio-system classifier — 24 documented classes",
            classes=_SIGIDWIKI_CLASSES,
            input_representation=CatalogInputRepresentation.SPECTROGRAM,
            preprocessing="Audio Spectrogram Transformer (AST)-style spectral representation; exact mel/STFT parameters not independently confirmed.",
            framework="PyTorch (Hugging Face Transformers, AST architecture)",
            original_format=CatalogOriginalFormat.SAFETENSORS,
            onnx_available=False,
            conversion_status=CatalogStatus.CONVERSION_REQUIRED,
            license="bsd-3-clause",
            priority="MUY ALTA",
            notes="Gated on Hugging Face -- requires accepting repository terms before download. Not a universal detector: a broad but finite radio-system classifier. Evaluate AST -> ONNX export via Hugging Face Optimum.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-MT-PREAMCNN",
            name="MT-PreamCNN",
            kind=CatalogEntryKind.MODEL,
            provider="lkk688 (Hugging Face)",
            source_url="https://huggingface.co/lkk688/mt-preamcnn",
            download_url="https://huggingface.co/lkk688/mt-preamcnn/resolve/main/onnx/mt_preamcnn_attn.onnx",
            task=CatalogTask.MODULATION_CLASSIFICATION,
            signal_domain="Joint packet detection + modulation classification + SNR estimation on OFDM preambles",
            input_representation=CatalogInputRepresentation.COMPLEX_IQ,
            input_length=800,
            input_shape=[None, 1600],
            preprocessing="800 complex I/Q samples as a 1600-float32 vector, real/imag interleaved.",
            framework="PyTorch",
            original_format=CatalogOriginalFormat.ONNX,
            onnx_available=True,
            conversion_status=CatalogStatus.READY,
            opset=17,
            reported_metrics={"modulation_accuracy_pct": 92.3, "note": "Attention variant, mixed training + phase augmentation, per HF model card"},
            priority="MUY ALTA",
            notes="ONNX exports ship directly in the repo's onnx/ directory (mt_preamcnn_attn.onnx, mt_preamcnn_cnn.onnx) with dynamic batch support -- no reconstruction from PyTorch needed. download_url points at the Attention variant (reports the higher accuracy); the CNN variant sits alongside it in the same folder.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-BACALHAUNET",
            name="BacalhauNet",
            kind=CatalogEntryKind.MODEL,
            provider="ITU AI/ML in 5G Challenge",
            source_url="https://github.com/ITU-AI-ML-in-5G-Challenge/ITU-ML5G-PS-007-BacalhauNet",
            download_url="https://raw.githubusercontent.com/ITU-AI-ML-in-5G-Challenge/ITU-ML5G-PS-007-BacalhauNet/main/bacalhaunet_gold_export.onnx",
            task=CatalogTask.MODULATION_CLASSIFICATION,
            dataset="RadioML 2018.01A",
            framework="PyTorch (Brevitas, quantization-aware training)",
            original_format=CatalogOriginalFormat.ONNX,
            onnx_available=True,
            conversion_status=CatalogStatus.READY,
            reported_metrics={"test_accuracy_pct": 56.24, "note": "ITU AI/ML in 5G Challenge submission, co-optimized for low inference cost -- not a general AMC performance benchmark"},
            priority="ALTA",
            notes="Publishes both bacalhaunet_gold_export.onnx (download_url above, verified HTTP 200 against raw.githubusercontent.com) and bacalhaunet_gold_weights.pth, both at repo root on the main branch. The ~56% accuracy reflects a competition scoring function that also rewards cheap inference, not a ceiling on AMC accuracy in general.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-CNN-LSTM-OTA",
            name="CNN-LSTM OTA RF Classifier",
            kind=CatalogEntryKind.MODEL,
            provider="krishna-ji (GitHub)",
            source_url="https://github.com/krishna-ji/automatic-rf-identification-for-intelligent-communication-using-cnn-lstm",
            download_url="https://raw.githubusercontent.com/krishna-ji/automatic-rf-identification-for-intelligent-communication-using-cnn-lstm/main/desktop-app/models/combined_model.onnx",
            task=CatalogTask.MODULATION_CLASSIFICATION,
            classes=["BPSK", "QPSK", "8PSK", "16QAM", "64QAM", "AM-DSB-SC", "AM-SSB-SC", "WBFM", "GMSK", "GFSK"],
            input_representation=CatalogInputRepresentation.IQ_FEATURES,
            input_length=1024,
            input_shape=[None, 224, 224, 3],
            preprocessing="1024 raw I/Q samples, normalized to [-1,1], windowed into 8 overlapping 224-sample segments, expanded into [I, Q, amplitude, phase] channels, reshaped to 224x224x3 for CNN input (per repo README; not independently re-derived).",
            framework="PyTorch/Keras (CNN + LSTM)",
            original_format=CatalogOriginalFormat.ONNX,
            onnx_available=True,
            conversion_status=CatalogStatus.READY,
            reported_metrics={"accuracy_pct": 93.48, "note": "Over-the-air validation across varying noise conditions, per repo README"},
            priority="ALTA",
            notes="ONNX export ships at desktop-app/models/combined_model.onnx (download_url above, verified HTTP 200).",
        ),
        RFModelCatalogEntry(
            id="CATALOG-INRIA-RFFI-ONNX",
            name="INRIA RF Fingerprinting ONNX Model Collection",
            kind=CatalogEntryKind.MODEL,
            provider="INRIA (Zenodo, unconfirmed record)",
            source_url="https://zenodo.org/search?q=RF%20fingerprinting%20ONNX%20physical%20layer%20authentication",
            task=CatalogTask.RF_FINGERPRINTING,
            signal_domain="Physical-layer device authentication (per-device classical-ML models: XGBoost/Random Forest/SVC/KNN/Logistic Regression), organized by trial/algorithm/feature-selection/device -- NOT signal-type classification.",
            input_representation=CatalogInputRepresentation.FEATURE_VECTOR,
            original_format=CatalogOriginalFormat.ONNX,
            conversion_status=CatalogStatus.RESEARCH_MODEL,
            validation_status="UNVERIFIED_SOURCE",
            independently_verified=False,
            priority="MUY ALTA para RFFI (pendiente de verificación de URL)",
            notes="This session could not locate the exact Zenodo record via web search -- source_url above is a real Zenodo search query, not a confirmed record page. Do not treat as READY or download from an assumed URL; confirm the exact DOI/record manually first.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-GR-SPECTRUMDETECT",
            name="TorchSig gr-spectrumdetect",
            kind=CatalogEntryKind.MODEL,
            provider="TorchDSP (GitHub)",
            source_url="https://github.com/TorchDSP/gr-spectrumdetect",
            task=CatalogTask.WIDEBAND_SIGNAL_DETECTION,
            signal_domain="Detects WHERE a signal exists in a wideband spectrogram -- does not classify protocol or modulation.",
            input_representation=CatalogInputRepresentation.SPECTROGRAM,
            input_shape=[1, 1024, 1024],
            preprocessing="1024x1024 grayscale spectrogram, black-hot color scheme.",
            framework="PyTorch (Ultralytics YOLO11S)",
            original_format=CatalogOriginalFormat.PYTORCH_PT,
            onnx_available=False,
            conversion_status=CatalogStatus.CONVERTIBLE,
            priority="MUY ALTA",
            notes="Checkpoint is named 11s.pt (fetched via trained_model_download.sh), not detect.pt. Convert via Ultralytics' own `model.export(format=\"onnx\")`.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-TORCHSIG-XCIT-NARROWBAND",
            name="TorchSig Models — XCiTClassifier (narrowband)",
            kind=CatalogEntryKind.MODEL,
            provider="TorchDSP (GitHub)",
            source_url="https://github.com/TorchDSP/torchsig-models",
            task=CatalogTask.MODULATION_CLASSIFICATION,
            signal_domain="Narrowband signal classification, 24 classes",
            input_representation=CatalogInputRepresentation.COMPLEX_IQ,
            framework="PyTorch (1D adaptation of XCiT)",
            original_format=CatalogOriginalFormat.PYTORCH_PT,
            onnx_available=False,
            conversion_status=CatalogStatus.CONVERSION_REQUIRED,
            priority="ALTA",
            notes="One of two concrete checkpoints in this repo (see also the YOLO11n wideband detector entry) -- registered separately rather than as one generic 'TorchSig' entry, per spec section 7. Exact checkpoint download link within the repo not yet located.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-TORCHSIG-YOLO11N-WIDEBAND",
            name="TorchSig Models — YOLO11n (wideband detector)",
            kind=CatalogEntryKind.MODEL,
            provider="TorchDSP (GitHub)",
            source_url="https://github.com/TorchDSP/torchsig-models",
            task=CatalogTask.WIDEBAND_SIGNAL_DETECTION,
            input_representation=CatalogInputRepresentation.SPECTROGRAM,
            framework="PyTorch (Ultralytics YOLO11n)",
            original_format=CatalogOriginalFormat.PYTORCH_PT,
            onnx_available=False,
            conversion_status=CatalogStatus.CONVERTIBLE,
            priority="ALTA",
            notes="Wideband detection sibling of the XCiT narrowband classifier in the same repo. Convert via Ultralytics' own ONNX exporter. Exact checkpoint download link within the repo not yet located.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-LWM-SPECTRO",
            name="LWM-Spectro",
            kind=CatalogEntryKind.MODEL,
            provider="wi-lab (Hugging Face)",
            source_url="https://huggingface.co/wi-lab/lwm-spectro",
            download_url="https://huggingface.co/wi-lab/lwm-spectro/resolve/main/moe_checkpoint.pth",
            task=CatalogTask.FOUNDATION_MODEL,
            signal_domain="Wireless foundation model / Mixture-of-Experts, protocol-specialized experts (LTE, WiFi, 5G) selected via a router.",
            input_representation=CatalogInputRepresentation.SPECTROGRAM,
            input_shape=[None, 128, 128],
            framework="PyTorch",
            original_format=CatalogOriginalFormat.CHECKPOINT,
            onnx_available=False,
            conversion_status=CatalogStatus.FOUNDATION_FINE_TUNING_REQUIRED,
            priority="MUY ALTA",
            notes="Checkpoint (moe_checkpoint.pth) plus per-expert weights (experts/*). Downstream uses documented: modulation classification, SNR recognition, mobility recognition. ONNX exportability not yet validated -- do not mark READY.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-WAVESFM",
            name="WavesFM",
            kind=CatalogEntryKind.MODEL,
            provider="ahmedaboulfo (Hugging Face + GitHub)",
            source_url="https://huggingface.co/ahmedaboulfo/wavesfm",
            download_url="https://huggingface.co/ahmedaboulfo/wavesfm/resolve/main/wavesfm-v1p0.pth",
            paper_url="https://arxiv.org/abs/2511.15162",
            task=CatalogTask.FOUNDATION_MODEL,
            signal_domain="Multimodal wireless foundation model (ViT encoder, masked wireless modeling) over IQ, spectrograms, CSI, and CIR.",
            input_representation=CatalogInputRepresentation.OTHER,
            framework="PyTorch",
            original_format=CatalogOriginalFormat.CHECKPOINT,
            onnx_available=False,
            conversion_status=CatalogStatus.FOUNDATION_FINE_TUNING_REQUIRED,
            priority="ALTA PARA INVESTIGACIÓN",
            notes="Checkpoint: wavesfm-v1p0.pth. Documented downstream tasks: RF fingerprinting, interference detection/classification, RF signal classification, RADCOM signal/modulation classification, 5G NR positioning, DeepMIMO LoS/NLoS prediction, UWB localization, human activity sensing (CSI). The base checkpoint is not itself a ready classifier for any single task -- downstream heads/fine-tuning required.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-SPECTRUMFM",
            name="SpectrumFM",
            kind=CatalogEntryKind.MODEL,
            provider="ChunyuLiu188 (GitHub)",
            source_url="https://github.com/ChunyuLiu188/SpectrumFM",
            task=CatalogTask.FOUNDATION_MODEL,
            signal_domain="Spectrum foundation model, self-supervised pretraining for spectrum management.",
            dataset="RML2018 (pretraining)",
            framework="PyTorch (transformer encoder, 16 layers, 4 heads, 256-dim latent)",
            original_format=CatalogOriginalFormat.UNKNOWN,
            onnx_available=False,
            conversion_status=CatalogStatus.FOUNDATION_FINE_TUNING_REQUIRED,
            priority="MUY ALTA PARA INVESTIGACIÓN",
            notes="Documented downstream tasks: Automatic Modulation Classification, Wireless Technology Classification, Spectrum Sensing, Anomaly Detection. Checkpoint format, license, and ONNX feasibility not yet independently verified -- needs manual download and inspection.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-AWN",
            name="AWN (Adaptive Wavelet Network)",
            kind=CatalogEntryKind.MODEL,
            provider="zjwfufu (GitHub)",
            source_url="https://github.com/zjwfufu/AWN",
            paper_url="https://doi.org/10.1109/TCCN.2023.3252580",
            task=CatalogTask.MODULATION_CLASSIFICATION,
            dataset="RML2016.10a, RML2016.10b, RML2018.01a (three separate pretrained checkpoints)",
            framework="PyTorch",
            original_format=CatalogOriginalFormat.UNKNOWN,
            onnx_available=False,
            conversion_status=CatalogStatus.CONVERSION_REQUIRED,
            priority="MEDIA/ALTA",
            notes="Zhang, Wang, Feng, Yang (2023), IEEE TCCN vol. 9, issue 3, pp. 549-563. Pretrained weights are hosted externally (Google Drive / Baidu Netdisk links in the repo README), not a direct file URL -- exact archive format not independently confirmed.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-META-TRANSFORMER-AMC",
            name="Meta-Transformer AMC",
            kind=CatalogEntryKind.MODEL,
            provider="cheeseBG (GitHub)",
            source_url="https://github.com/cheeseBG/meta-transformer-amc",
            paper_url="https://doi.org/10.1109/ACCESS.2024.3352634",
            task=CatalogTask.MODULATION_CLASSIFICATION,
            signal_domain="Few-shot modulation classification -- generalizes to unseen modulations from a small number of samples.",
            dataset="RadioML2018.01A",
            framework="PyTorch (transformer-based meta-learning)",
            original_format=CatalogOriginalFormat.UNKNOWN,
            onnx_available=False,
            conversion_status=CatalogStatus.CONVERSION_REQUIRED,
            priority="INVESTIGACIÓN",
            notes="Jang, Pyo, Yoon, Choi (2024), IEEE Access. Pretrained weights hosted externally via a Google Drive link in the repo README, not a direct file URL.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-T-PRIME",
            name="T-PRIME",
            kind=CatalogEntryKind.MODEL,
            provider="genesys-neu (GitHub)",
            source_url="https://github.com/genesys-neu/t-prime",
            task=CatalogTask.PROTOCOL_IDENTIFICATION,
            classes=["802.11ax", "802.11b", "802.11n", "802.11g"],
            framework="PyTorch (T-PRIME Transformer, CNN1D, ResNet, AMCNet, MCFormer)",
            original_format=CatalogOriginalFormat.PYTORCH_PT,
            onnx_available=False,
            conversion_status=CatalogStatus.RESEARCH_MODEL,
            notes="Checkpoint paths (TPrime_transformer/model_cp/tprime_lg.pt, tprime_sm.pt) are referenced in the codebase, but this session could not confirm a committed, downloadable checkpoint versus one expected to be produced locally by training. Do not treat as READY until a concrete downloadable checkpoint is located, per the original research's own caveat.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-PCICN-RFFI",
            name="PCICN RF Fingerprinting",
            kind=CatalogEntryKind.MODEL,
            provider="Hsuan-Tung (GitHub)",
            source_url="https://github.com/Hsuan-Tung/PCICN_RFFingerprinting",
            download_url="https://raw.githubusercontent.com/Hsuan-Tung/PCICN_RFFingerprinting/main/pretrained/output_model_PRNN_CNN_pretrained.pth",
            task=CatalogTask.RF_FINGERPRINTING,
            signal_domain="RF fingerprinting of 30 ZigBee transmitters (Naval Research Laboratory raw data, Princeton-preprocessed).",
            framework="PyTorch (PRNN-CNN, NRL-CNN)",
            original_format=CatalogOriginalFormat.PYTORCH_PTH,
            onnx_available=False,
            conversion_status=CatalogStatus.CONVERSION_REQUIRED,
            reported_metrics={
                "PRNN_CNN_accuracy_pct": 96.32, "PRNN_CNN_params": 6302, "PRNN_CNN_latency_ms_pynq_z1": 0.219,
                "NRL_CNN_accuracy_pct": 95.17, "NRL_CNN_params": 322602, "NRL_CNN_latency_ms_pynq_z1": 26.19,
                "note": "Per repo README, PYNQ-Z1 hardware benchmark",
            },
            priority="ALTA para fingerprinting",
            notes="Two pretrained checkpoints ship directly under pretrained/ on the main branch: output_model_PRNN_CNN_pretrained.pth (download_url above, verified HTTP 200 -- the higher-accuracy, lower-latency of the two) and output_model_NRL_CNN_pretrained.pth.",
        ),
        RFModelCatalogEntry(
            id="CATALOG-DEEPSIG-RADIOML",
            name="DeepSig RadioML",
            kind=CatalogEntryKind.DATASET,
            provider="DeepSig Inc.",
            source_url="https://www.deepsig.ai/datasets",
            download_url="https://www.deepsig.ai/datasets",
            conversion_status=CatalogStatus.DATASET_ONLY,
            priority=None,
            notes="Not a model. The standard modulation-classification dataset (RML2016/2018) that most published AMC models (BacalhauNet, AWN, Meta-Transformer AMC, SpectrumFM's pretraining, ...) are trained or evaluated on -- listed here as a training/evaluation resource, never as something 'downloadable and runnable' the way a model is.",
        ),
    ]
