import React, { useEffect, useMemo, useState } from 'react';
import { ApiService } from '../../app/services/ApiService';
import { useAnalyzerSettings, useMarkers } from '../../app/store/AppStore';
import { FingerprintingCaptureRecord, ModulatedSignalCapture } from '../../shared/types';

const api = new ApiService();

const splitHelp = {
  train: {
    title: 'Training',
    description:
      'Se usa para ajustar el modelo. No debe reutilizarse luego como validacion externa ni como prediccion final.',
    destination: 'fingerprinting/train',
  },
  val: {
    title: 'Validation',
    description:
      'Se reserva para medir rendimiento fuera del entrenamiento. Debe mantenerse aislada de train.',
    destination: 'fingerprinting/val',
  },
  predict: {
    title: 'Prediction',
    description:
      'Se usa para inferencia o verificacion sobre capturas nuevas. No debe contaminar train ni val.',
    destination: 'fingerprinting/predict',
  },
} as const;

const experimentGuidance = {
  operational: {
    title: 'Operational fingerprinting baseline',
    task: 'Closed-set device profile managed by the current model registry.',
    recommendedFormat: '.cfile or .iq with paired .json metadata',
    labelField: 'transmitter_id',
    reason: 'Use this when the capture will feed the existing Dataset Builder, validation and operational inference workflow.',
  },
  e1: {
    title: 'E1 Raw IQ CNN 1D',
    task: 'Stage 2 device fingerprinting.',
    recommendedFormat: 'raw IQ as .cfile or .iq, complex64, enough duration for many [2, N] windows',
    labelField: 'transmitter_id',
    reason: 'E1 learns directly from I and Q samples, so raw IQ and stable transmitter labels are mandatory.',
  },
  e3: {
    title: 'E3 Spectrogram/Waterfall CNN 2D',
    task: 'Closed-set signal recognition or device fingerprinting from time-frequency images.',
    recommendedFormat: 'raw IQ .cfile/.iq preferred; spectrogram/waterfall will be generated reproducibly later',
    labelField: 'transmitter_id, signal_type or modulation_class',
    reason: 'E3 compares RF image representations generated from the same capture metadata and split strategy.',
  },
  e5: {
    title: 'E5 Spectral Feature Baseline',
    task: 'Explainable classical ML baseline from PSD and spectral descriptors.',
    recommendedFormat: 'raw IQ .cfile/.iq preferred; features are extracted reproducibly from IQ',
    labelField: 'transmitter_id, signal_type or modulation_class',
    reason: 'E5 needs enough spectral diversity and clean metadata to interpret PSD, bandwidth, entropy and energy ratios.',
  },
  rsu: {
    title: 'RF Signal Understanding',
    task: 'Signal family, modulation-like or protocol-like understanding, not physical transmitter fingerprinting.',
    recommendedFormat: '.iq/.cfile complex64 plus signal_type or modulation_class label',
    labelField: 'signal_type or modulation_class',
    reason: 'Use this when the model should learn what kind of signal it is, not which physical transmitter emitted it.',
  },
} as const;

const supportedDatasetFormats = [
  ['.cfile + .json', 'Primary local IQ package for Capture Lab, E1, E3 and E5.'],
  ['.iq + .json', 'Equivalent raw IQ package; useful for RF Signal Understanding and experiment import.'],
  ['.sigmf-data + .sigmf-meta', 'Reproducible interchange/export format; generated by RF Experiment Lab exporter.'],
  ['.npy / .npz', 'Representation artifacts or custom external datasets.'],
  ['.h5 / .hdf5', 'Experiment manifest/export target; binary writing remains optional.'],
  ['.mat / .pkl / .csv', 'External MATLAB, Pickle or tabular feature datasets.'],
  ['.png / .jpg / .npy images', 'Imported spectrogram/waterfall image datasets for E3-style workflows.'],
] as const;

const qcProfiles = {
  exploratory: {
    title: 'Exploratory',
    text: 'Flexible capture for discovery. Saves as needs_review and not_ready, even with moderate warnings or missing final label.',
  },
  training_draft: {
    title: 'Training Draft',
    text: 'Intermediate collection. Allows moderate warnings, but requires detectable signal and minimum metadata; manual review remains required.',
  },
  scientific: {
    title: 'Scientific',
    text: 'Strict capture for reproducible training. Requires strong label, valid QC, complete metadata and task consistency.',
  },
  manual_override: {
    title: 'Manual Override',
    text: 'Stores evidence even if QC fails. Requires a reason and is never automatically scientific training-ready.',
  },
} as const;

const defaultForm = {
  session_id: 'session_001',
  dataset_split: 'train' as 'train' | 'val' | 'predict',
  capture_config: {
    device_source: 'uhd',
    sdr_model: 'USRP-B200',
    sdr_serial: 'unknown',
    gain_stage: 'manual',
    antenna_port: 'RX2',
    capture_type: 'iq_file',
    center_frequency_hz: 433920000,
    sample_rate_hz: 2000000,
    effective_bandwidth_hz: 2000000,
    frontend_bandwidth_hz: 2000000,
    gain_mode: 'manual',
    gain_settings: {
      lna_db: 20,
      vga_db: 0,
      if_db: 0,
      composite_gain_db: 20,
    },
    ppm_correction: 0,
    lo_offset_hz: 0,
    capture_duration_s: 2,
    sample_count: 0,
    file_format: 'cfile',
    sample_dtype: 'complex64',
    byte_order: 'native',
    channel_count: 1,
    output_path: '',
    dataset_destination: splitHelp.train.destination as string,
  },
  transmitter: {
    transmitter_label: 'band_profile_pending',
    transmitter_class: 'profile_pending',
    transmitter_id: 'weak_profile_pending',
    family: 'profile_pending',
    signal_type: 'profile_pending',
    modulation_class: 'profile_pending',
    protocol_family: 'profile_pending',
    band_label: '',
    profile_key: '',
    ground_truth_confidence: 'weak_from_band_profile',
  },
  scenario: {
    operator: 'operator_a',
    environment: 'indoor_lab_los',
    distance_m: 2,
    line_of_sight: true,
    indoor: true,
    notes: '',
    session_number: 1,
  },
  quality_metrics: {
    estimated_snr_db: 18,
    noise_floor_db: -96,
    peak_power_db: -24,
    average_power_db: -35,
    occupied_bandwidth_hz: 180000,
    peak_frequency_hz: 433920120,
    frequency_offset_hz: 120,
    clipping_pct: 0,
    sample_drop_count: 0,
    buffer_overflow_count: 0,
    silence_pct: 4,
    peak_to_average_ratio_db: 11,
    kurtosis: 2.8,
    burst_duration_ms: 42,
  },
  burst_detection: {
    method: 'energy_threshold',
    energy_threshold_db: -42,
    pre_trigger_samples: 4096,
    post_trigger_samples: 8192,
    min_burst_duration_ms: 1,
    max_burst_duration_ms: 120,
    burst_count: 1,
    regions_of_interest: ['transient_start', 'whole_burst'],
    burst_start_sample: 4096,
    burst_end_sample: 98304,
  },
  artifacts: {
    iq_file: '',
    metadata_file: '',
    sha256: '',
  },
  operator_decision: 'valid',
  review_notes: '',
  export_windows: ['transient_start', 'whole_burst'],
  qc_policy_profile: 'scientific' as keyof typeof qcProfiles,
  qc_thresholds: {
    min_snr_db: 12,
    max_clipping_percentage: 0.5,
    min_occupied_bandwidth_hz: 1,
    max_occupied_bandwidth_hz: 0,
    max_frequency_offset_hz: 5000,
    min_signal_duration_ms: 1,
    max_silence_percentage: 85,
    require_label: true,
    require_metadata: true,
    allow_weak_label: false,
    allow_unlabeled: false,
    allow_manual_override: false,
  },
  label_status: 'weak_label' as 'unlabeled' | 'weak_label' | 'strong_label',
  manual_override_reason: '',
};

const sectionClass =
  'rounded-[1.75rem] border border-slate-200 bg-white/90 p-5 shadow-[0_18px_40px_rgba(15,23,42,0.08)]';
const labelClass = 'text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500';
const inputClass =
  'mt-2 w-full rounded-2xl border border-slate-300 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:bg-white';

export const GuidedCaptureView: React.FC = () => {
  const markers = useMarkers();
  const analyzerSettings = useAnalyzerSettings();
  const [form, setForm] = useState(defaultForm);
  const [experimentTarget, setExperimentTarget] = useState<keyof typeof experimentGuidance>('e1');
  const [captures, setCaptures] = useState<FingerprintingCaptureRecord[]>([]);
  const [modulatedCaptures, setModulatedCaptures] = useState<ModulatedSignalCapture[]>([]);
  const [message, setMessage] = useState<string>('');
  const [postCaptureExport, setPostCaptureExport] = useState<Record<string, any> | null>(null);
  const [bandProfileSuggestion, setBandProfileSuggestion] = useState<Record<string, any> | null>(null);
  const [autoApplyBandProfile, setAutoApplyBandProfile] = useState(true);

  const activeSplit = splitHelp[form.dataset_split as keyof typeof splitHelp];
  const activeExperiment = experimentGuidance[experimentTarget];
  const markerBand = useMemo(() => {
    if (markers.length < 2) return null;
    const first = markers[0];
    const second = markers[1];
    const start = Math.min(first.frequency, second.frequency);
    const stop = Math.max(first.frequency, second.frequency);
    if (!Number.isFinite(start) || !Number.isFinite(stop) || stop <= start) return null;
    return {
      start,
      stop,
      center: (start + stop) / 2,
      bandwidth: stop - start,
    };
  }, [markers]);

  const refresh = async () => {
    const [fingerprintingCaptures, modulated] = await Promise.all([
      api.getFingerprintingCaptures(),
      api.getModulatedSignalCaptures(),
    ]);
    setCaptures(fingerprintingCaptures);
    setModulatedCaptures(modulated.slice(0, 6));
  };

  useEffect(() => {
    refresh().catch((error) => console.error('Failed to load guided capture data', error));
  }, []);

  const applyBandProfileDefaults = (suggestion: Record<string, any> | null = bandProfileSuggestion) => {
    const defaults = suggestion?.data?.defaults ?? suggestion?.defaults;
    if (!defaults) return;
    setForm((current) => ({
      ...current,
      label_status: 'weak_label',
      capture_config: {
        ...current.capture_config,
        center_frequency_hz: markerBand?.center ?? current.capture_config.center_frequency_hz,
        effective_bandwidth_hz: markerBand?.bandwidth ?? current.capture_config.effective_bandwidth_hz,
        frontend_bandwidth_hz: markerBand?.bandwidth ?? current.capture_config.frontend_bandwidth_hz,
      },
      quality_metrics: {
        ...current.quality_metrics,
        occupied_bandwidth_hz: markerBand?.bandwidth ?? current.quality_metrics.occupied_bandwidth_hz,
        peak_frequency_hz: markerBand?.center ?? current.quality_metrics.peak_frequency_hz,
      },
      transmitter: {
        ...current.transmitter,
        transmitter_label: defaults.transmitter_label || current.transmitter.transmitter_label,
        transmitter_class: defaults.transmitter_class || current.transmitter.transmitter_class,
        transmitter_id: defaults.transmitter_id || current.transmitter.transmitter_id,
        family: defaults.family || current.transmitter.family,
        signal_type: defaults.signal_type || defaults.transmitter_class || current.transmitter.signal_type,
        modulation_class: defaults.modulation_class || current.transmitter.modulation_class,
        protocol_family: defaults.protocol_family || current.transmitter.protocol_family,
        band_label: defaults.band_label || current.transmitter.band_label,
        profile_key: defaults.profile_key || current.transmitter.profile_key,
        ground_truth_confidence: defaults.ground_truth_confidence || 'weak_from_band_profile',
      },
      scenario: {
        ...current.scenario,
        notes: current.scenario.notes || `Weak band-profile label from ${defaults.profile_key || 'band_profiles.json'}. Confirm manually before scientific training.`,
      },
    }));
  };

  useEffect(() => {
    const payload = markerBand
      ? {
          start_frequency_hz: markerBand.start,
          stop_frequency_hz: markerBand.stop,
          center_frequency_hz: markerBand.center,
          bandwidth_hz: markerBand.bandwidth,
        }
      : {
          center_frequency_hz: form.capture_config.center_frequency_hz || analyzerSettings.centerFrequency,
          bandwidth_hz: form.capture_config.effective_bandwidth_hz || analyzerSettings.span,
        };
    let cancelled = false;
    api.resolveRFIntelligenceBandProfile(payload)
      .then((response) => {
        if (cancelled) return;
        setBandProfileSuggestion(response.data ?? response);
        if (autoApplyBandProfile) applyBandProfileDefaults(response.data ?? response);
      })
      .catch((error) => console.error('Failed to resolve RF band profile', error));
    return () => {
      cancelled = true;
    };
  }, [
    markerBand?.start,
    markerBand?.stop,
    form.capture_config.center_frequency_hz,
    form.capture_config.effective_bandwidth_hz,
    analyzerSettings.centerFrequency,
    analyzerSettings.span,
    autoApplyBandProfile,
  ]);

  const setNested = (section: keyof typeof form, field: string, value: unknown) => {
    setForm((current) => ({
      ...current,
      [section]: {
        ...(current[section] as Record<string, unknown>),
        [field]: value,
      },
    }));
  };

  const setGainSetting = (field: string, value: number) => {
    setForm((current) => ({
      ...current,
      capture_config: {
        ...current.capture_config,
        gain_settings: {
          ...current.capture_config.gain_settings,
          [field]: value,
        },
      },
    }));
  };

  const setDatasetSplit = (datasetSplit: 'train' | 'val' | 'predict') => {
    setForm((current) => ({
      ...current,
      dataset_split: datasetSplit,
      capture_config: {
        ...current.capture_config,
        dataset_destination: splitHelp[datasetSplit].destination,
      },
    }));
  };

  const setExperiment = (target: keyof typeof experimentGuidance) => {
    setExperimentTarget(target);
    const guidance = experimentGuidance[target];
    setForm((current) => ({
      ...current,
      transmitter: {
        ...current.transmitter,
        transmitter_class: target === 'rsu' ? 'signal_type_or_modulation_class' : current.transmitter.transmitter_class,
        family: target === 'rsu' ? 'signal_recognition' : current.transmitter.family,
      },
      scenario: {
        ...current.scenario,
        notes: current.scenario.notes || `Intended use: ${guidance.title}. Label field: ${guidance.labelField}.`,
      },
    }));
  };

  const setQcProfile = (profile: keyof typeof qcProfiles) => {
    const thresholds =
      profile === 'exploratory'
        ? { min_snr_db: 3, max_clipping_percentage: 5, min_occupied_bandwidth_hz: 0, max_occupied_bandwidth_hz: 0, max_frequency_offset_hz: 100000, min_signal_duration_ms: 0, max_silence_percentage: 95, require_label: false, require_metadata: false, allow_weak_label: true, allow_unlabeled: true, allow_manual_override: false }
        : profile === 'training_draft'
          ? { min_snr_db: 6, max_clipping_percentage: 2, min_occupied_bandwidth_hz: 0, max_occupied_bandwidth_hz: 0, max_frequency_offset_hz: 50000, min_signal_duration_ms: 1, max_silence_percentage: 90, require_label: false, require_metadata: true, allow_weak_label: true, allow_unlabeled: true, allow_manual_override: false }
          : profile === 'manual_override'
            ? { min_snr_db: 0, max_clipping_percentage: 100, min_occupied_bandwidth_hz: 0, max_occupied_bandwidth_hz: 0, max_frequency_offset_hz: 0, min_signal_duration_ms: 0, max_silence_percentage: 100, require_label: false, require_metadata: false, allow_weak_label: true, allow_unlabeled: true, allow_manual_override: true }
            : { min_snr_db: 12, max_clipping_percentage: 0.5, min_occupied_bandwidth_hz: 1, max_occupied_bandwidth_hz: 0, max_frequency_offset_hz: 5000, min_signal_duration_ms: 1, max_silence_percentage: 85, require_label: true, require_metadata: true, allow_weak_label: false, allow_unlabeled: false, allow_manual_override: false };
    setForm((current) => ({ ...current, qc_policy_profile: profile, qc_thresholds: thresholds }));
  };

  const setQcThreshold = (field: string, value: unknown) => {
    setForm((current) => ({
      ...current,
      qc_thresholds: {
        ...current.qc_thresholds,
        [field]: value,
      },
    }));
  };

  const submit = async () => {
    try {
      await api.createFingerprintingCapture({
        ...form,
        signal_family: form.transmitter.family,
      });
      setMessage(`Scientific capture manifest stored as ${form.dataset_split}.`);
      await refresh();
    } catch (error) {
      console.error(error);
      setMessage('Failed to store scientific capture manifest.');
    }
  };

  const saveRFExperimentSample = async () => {
    const iqPath = form.artifacts.iq_file || form.capture_config.output_path;
    if (!iqPath) {
      setMessage('Set an IQ file path before creating an RF Experiment Lab sample.');
      return;
    }
    try {
      await api.createRFExperimentInternalSample({
        iq_path: iqPath,
        sample_id: `${form.session_id}_${form.transmitter.transmitter_id}_${Date.now()}`,
        task: experimentTarget === 'rsu' ? 'signal_recognition' : 'device_fingerprinting',
        label:
          experimentTarget === 'rsu'
            ? form.transmitter.transmitter_class
            : form.transmitter.transmitter_id,
        label_type: experimentTarget === 'rsu' ? 'signal_type' : 'transmitter_id',
        transmitter_id: form.transmitter.transmitter_id,
        signal_type: form.transmitter.transmitter_class,
        modulation_class: form.transmitter.family,
        session_id: form.session_id,
        receiver_id: form.capture_config.sdr_serial,
        environment_id: form.scenario.environment,
        distance_m: form.scenario.distance_m,
        datatype: form.capture_config.sample_dtype,
        sample_rate_hz: form.capture_config.sample_rate_hz,
        center_frequency_hz: form.capture_config.center_frequency_hz,
        start_frequency_hz: form.capture_config.center_frequency_hz - form.capture_config.effective_bandwidth_hz / 2,
        stop_frequency_hz: form.capture_config.center_frequency_hz + form.capture_config.effective_bandwidth_hz / 2,
        duration_seconds: form.capture_config.capture_duration_s,
        split_group: form.session_id,
        qc_summary: {
          qc_status: form.operator_decision,
          snr_db: form.quality_metrics.estimated_snr_db,
          clipping_detected: Number(form.quality_metrics.clipping_pct) > 0,
          occupied_bandwidth_hz: form.quality_metrics.occupied_bandwidth_hz,
          signal_centering_error_hz: form.quality_metrics.frequency_offset_hz,
        },
      });
      setMessage('RF Experiment Lab internal sample created. Open RF Experiment Lab to review and export RFExperimentDatasetV1.');
    } catch (error) {
      console.error(error);
      setMessage('Failed to create RF Experiment Lab internal sample. Check that the IQ file exists.');
    }
  };

  const postCapturePayload = () => ({
    iq_path: form.artifacts.iq_file || form.capture_config.output_path,
    cfile_path: form.capture_config.file_format === 'cfile' ? (form.artifacts.iq_file || form.capture_config.output_path) : undefined,
    metadata_path: form.artifacts.metadata_file,
    dataset_id: 'capture_lab_export',
    dataset_version: `${form.session_id}_${form.transmitter.transmitter_id}`,
    representations: ['raw_iq', 'fft_psd', 'spectrogram', 'waterfall'],
    split_strategy: 'session_disjoint',
    label_schema: {
      label_field: experimentTarget === 'rsu' ? 'signal_type' : 'transmitter_id',
      label: experimentTarget === 'rsu' ? form.transmitter.transmitter_class : form.transmitter.transmitter_id,
    },
    window_size_samples: 65536,
    overlap: 0,
    n_fft: 1024,
    hop_length: 512,
  });

  const requireRawAndMetadata = () => {
    const payload = postCapturePayload();
    if (!payload.iq_path || !payload.metadata_path) {
      setMessage('Set both IQ file and metadata file paths before exporting derived dataset formats.');
      return null;
    }
    return payload;
  };

  const runPostCaptureExport = async (
    action: 'sigmf_preview' | 'sigmf_export' | 'hdf5_preview' | 'hdf5_export' | 'raw-iq' | 'fft-psd' | 'spectrogram' | 'waterfall' | 'manifest',
  ) => {
    const payload = requireRawAndMetadata();
    if (!payload) return;
    try {
      const response =
        action === 'sigmf_preview'
          ? await api.previewRFExperimentSigMF(payload)
          : action === 'sigmf_export'
            ? await api.exportRFExperimentSigMF(payload)
            : action === 'hdf5_preview'
              ? await api.previewRFExperimentHDF5Manifest(payload)
              : action === 'hdf5_export'
                ? await api.exportRFExperimentHDF5Manifest(payload)
                : action === 'manifest'
                  ? await api.exportRFExperimentRepresentationManifest(payload)
                  : await api.exportRFExperimentRepresentation(action, payload);
      setPostCaptureExport(response.data ?? response);
      setMessage(`Post-capture export completed: ${action}`);
    } catch (error) {
      console.error(error);
      setMessage(`Post-capture export failed: ${action}`);
    }
  };

  const importCapture = async (capture: ModulatedSignalCapture) => {
    try {
      await api.importModulatedCaptureToFingerprinting(capture.id, {
        session_id: form.session_id,
        dataset_split: form.dataset_split,
        transmitter_label: form.transmitter.transmitter_label,
        transmitter_class: form.transmitter.transmitter_class,
        transmitter_id: form.transmitter.transmitter_id,
        operator: form.scenario.operator,
        environment: form.scenario.environment,
        notes: form.scenario.notes,
        ground_truth_confidence: form.transmitter.ground_truth_confidence,
        family: form.transmitter.family,
        signal_family: form.transmitter.family,
        signal_type: form.transmitter.signal_type || form.transmitter.transmitter_class,
        modulation_class: form.transmitter.modulation_class,
        protocol_family: form.transmitter.protocol_family,
        band_label: form.transmitter.band_label,
        profile_key: form.transmitter.profile_key || null,
        label_status: form.label_status,
      });
      setMessage(`Imported modulated capture ${capture.id} as ${form.dataset_split}.`);
      await refresh();
    } catch (error) {
      console.error(error);
      setMessage(`Failed to import modulated capture ${capture.id}.`);
    }
  };

  return (
    <div className="min-h-full bg-[linear-gradient(180deg,_#f7fafc,_#edf6f3)] p-6">
      <div className="mb-6 flex flex-wrap items-end justify-between gap-4">
        <div>
          <div className="text-sm font-semibold uppercase tracking-[0.2em] text-teal-700">Guided Capture</div>
          <h1 className="mt-2 font-serif text-4xl text-slate-900">Adquisicion rigurosa, no grabacion indiscriminada</h1>
          <p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">
            Esta vista obliga a separar configuracion SDR, identidad del emisor, escenario de adquisicion, split del
            dataset, burst detection y control de calidad. El objetivo es que el modelo aprenda el transmisor, no el setup.
          </p>
        </div>
        <div className="rounded-full border border-slate-300 bg-white px-4 py-2 text-sm text-slate-700">{message}</div>
      </div>

      <div className="grid gap-5 xl:grid-cols-[1.25fr_0.95fr]">
        <div className="space-y-5">
          <section className={sectionClass}>
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div>
                <div className={labelClass}>Capture intent / dataset split</div>
                <p className="mt-2 max-w-3xl text-sm leading-7 text-slate-600">
                  Antes de capturar tienes que declarar si esta muestra es para entrenamiento, validacion externa o prediccion.
                  Esa decision afecta como se debe usar despues y evita fugas entre fases experimentales.
                </p>
              </div>
              <div className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700">
                Current destination: <span className="font-mono text-xs">{activeSplit.destination}</span>
              </div>
            </div>
            <div className="mt-5 grid gap-4 md:grid-cols-3">
              {(['train', 'val', 'predict'] as const).map((split) => (
                <button
                  key={split}
                  type="button"
                  onClick={() => setDatasetSplit(split)}
                  className={`rounded-[1.5rem] border p-5 text-left transition ${
                    form.dataset_split === split
                      ? 'border-slate-900 bg-slate-950 text-white'
                      : 'border-slate-200 bg-slate-50 text-slate-900 hover:bg-white'
                  }`}
                >
                  <div className="text-xs font-semibold uppercase tracking-[0.18em] opacity-80">{splitHelp[split].title}</div>
                  <p className="mt-3 text-sm leading-6 opacity-90">{splitHelp[split].description}</p>
                </button>
              ))}
            </div>
          </section>

          <section className={sectionClass}>
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div>
                <div className={labelClass}>QC strictness before capture</div>
                <h2 className="mt-2 text-xl font-semibold text-slate-900">{qcProfiles[form.qc_policy_profile].title}</h2>
                <p className="mt-2 max-w-3xl text-sm leading-7 text-slate-600">{qcProfiles[form.qc_policy_profile].text}</p>
              </div>
              <label className="min-w-56">
                <div className={labelClass}>Label status</div>
                <select className={inputClass} value={form.label_status} onChange={(event) => setForm((current) => ({ ...current, label_status: event.target.value as any }))}>
                  <option value="unlabeled">unlabeled</option>
                  <option value="weak_label">weak_label</option>
                  <option value="strong_label">strong_label</option>
                </select>
              </label>
            </div>
            <div className="mt-5 grid gap-3 md:grid-cols-4">
              {(Object.keys(qcProfiles) as Array<keyof typeof qcProfiles>).map((profile) => (
                <button
                  key={profile}
                  type="button"
                  onClick={() => setQcProfile(profile)}
                  className={`rounded-2xl border p-4 text-left text-sm transition ${
                    form.qc_policy_profile === profile ? 'border-slate-900 bg-slate-950 text-white' : 'border-slate-200 bg-slate-50 text-slate-800 hover:bg-white'
                  }`}
                >
                  <div className="font-semibold">{qcProfiles[profile].title}</div>
                  <div className="mt-2 text-xs opacity-80">{qcProfiles[profile].text}</div>
                </button>
              ))}
            </div>
            <div className="mt-4 grid gap-3 md:grid-cols-4">
              {[
                ['min_snr_db', 'Min SNR dB'],
                ['max_clipping_percentage', 'Max clipping %'],
                ['min_occupied_bandwidth_hz', 'Min occupied BW Hz'],
                ['max_occupied_bandwidth_hz', 'Max occupied BW Hz'],
                ['max_frequency_offset_hz', 'Max frequency offset Hz'],
                ['min_signal_duration_ms', 'Min signal duration ms'],
                ['max_silence_percentage', 'Max silence %'],
              ].map(([field, label]) => (
                <label key={field}>
                  <div className={labelClass}>{label}</div>
                  <input className={inputClass} type="number" value={Number((form.qc_thresholds as any)[field])} onChange={(event) => setQcThreshold(field, Number(event.target.value))} />
                </label>
              ))}
              {[
                ['require_label', 'Require label'],
                ['require_metadata', 'Require metadata'],
                ['allow_weak_label', 'Allow weak label'],
                ['allow_unlabeled', 'Allow unlabeled'],
                ['allow_manual_override', 'Allow manual override'],
              ].map(([field, label]) => (
                <label key={field} className="flex items-center gap-2 rounded-2xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-700">
                  <input type="checkbox" checked={Boolean((form.qc_thresholds as any)[field])} onChange={(event) => setQcThreshold(field, event.target.checked)} />
                  {label}
                </label>
              ))}
            </div>
            {form.qc_policy_profile === 'manual_override' && (
              <label className="mt-4 block">
                <div className={labelClass}>Manual override reason required</div>
                <textarea className={`${inputClass} min-h-20`} value={form.manual_override_reason} onChange={(event) => setForm((current) => ({ ...current, manual_override_reason: event.target.value }))} />
              </label>
            )}
          </section>

          <section className={sectionClass}>
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div>
                <div className={labelClass}>Experiment target</div>
                <h2 className="mt-2 text-xl font-semibold text-slate-900">{activeExperiment.title}</h2>
                <p className="mt-2 max-w-3xl text-sm leading-7 text-slate-600">
                  Select the scientific destination before saving the manifest. This does not change the capture backend; it guides
                  labels, format choices and the later RFExperimentDatasetV1 export.
                </p>
              </div>
              <div className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700">
                Label field: <span className="font-semibold">{activeExperiment.labelField}</span>
              </div>
            </div>
            <div className="mt-5 grid gap-3 md:grid-cols-5">
              {(Object.keys(experimentGuidance) as Array<keyof typeof experimentGuidance>).map((target) => (
                <button
                  key={target}
                  type="button"
                  onClick={() => setExperiment(target)}
                  className={`rounded-2xl border p-4 text-left text-sm transition ${
                    experimentTarget === target
                      ? 'border-slate-900 bg-slate-950 text-white'
                      : 'border-slate-200 bg-slate-50 text-slate-800 hover:bg-white'
                  }`}
                >
                  <div className="font-semibold">{experimentGuidance[target].title}</div>
                  <div className="mt-2 text-xs opacity-80">{experimentGuidance[target].task}</div>
                </button>
              ))}
            </div>
            <div className="mt-4 grid gap-3 md:grid-cols-3">
              <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700">
                <div className={labelClass}>Recommended data</div>
                <p className="mt-2 leading-6">{activeExperiment.recommendedFormat}</p>
              </div>
              <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700">
                <div className={labelClass}>Why</div>
                <p className="mt-2 leading-6">{activeExperiment.reason}</p>
              </div>
              <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">
                <div className={labelClass}>Leakage warning</div>
                <p className="mt-2 leading-6">
                  For E1/E3/E5, prefer session-disjoint or capture-disjoint exports later. Random split is only a quick debug check.
                </p>
              </div>
            </div>
          </section>

          <section className={sectionClass}>
            <div className="grid gap-4 md:grid-cols-3">
              <label>
                <div className={labelClass}>Device / SDR source</div>
                <input className={inputClass} value={form.capture_config.device_source} onChange={(e) => setNested('capture_config', 'device_source', e.target.value)} />
              </label>
              <label>
                <div className={labelClass}>SDR model</div>
                <input className={inputClass} value={form.capture_config.sdr_model} onChange={(e) => setNested('capture_config', 'sdr_model', e.target.value)} />
              </label>
              <label>
                <div className={labelClass}>Serial</div>
                <input className={inputClass} value={form.capture_config.sdr_serial} onChange={(e) => setNested('capture_config', 'sdr_serial', e.target.value)} />
              </label>
              <label>
                <div className={labelClass}>Center frequency (Hz)</div>
                <input className={inputClass} type="number" value={form.capture_config.center_frequency_hz} onChange={(e) => setNested('capture_config', 'center_frequency_hz', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>Sample rate (Hz)</div>
                <input className={inputClass} type="number" value={form.capture_config.sample_rate_hz} onChange={(e) => setNested('capture_config', 'sample_rate_hz', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>Effective bandwidth (Hz)</div>
                <input className={inputClass} type="number" value={form.capture_config.effective_bandwidth_hz} onChange={(e) => setNested('capture_config', 'effective_bandwidth_hz', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>Capture duration (s)</div>
                <input className={inputClass} type="number" value={form.capture_config.capture_duration_s} onChange={(e) => setNested('capture_config', 'capture_duration_s', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>File format</div>
                <select className={inputClass} value={form.capture_config.file_format} onChange={(e) => setNested('capture_config', 'file_format', e.target.value)}>
                  <option value="cfile">cfile</option>
                  <option value="iq">iq</option>
                </select>
              </label>
              <label>
                <div className={labelClass}>Sample dtype</div>
                <select className={inputClass} value={form.capture_config.sample_dtype} onChange={(e) => setNested('capture_config', 'sample_dtype', e.target.value)}>
                  <option value="complex64">complex64</option>
                  <option value="cf32_le">cf32_le</option>
                </select>
              </label>
              <label>
                <div className={labelClass}>PPM correction</div>
                <input className={inputClass} type="number" value={form.capture_config.ppm_correction} onChange={(e) => setNested('capture_config', 'ppm_correction', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>LO offset (Hz)</div>
                <input className={inputClass} type="number" value={form.capture_config.lo_offset_hz} onChange={(e) => setNested('capture_config', 'lo_offset_hz', Number(e.target.value))} />
              </label>
            </div>
            <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4">
              <div className={labelClass}>Dataset formats expected by current and experimental workflows</div>
              <div className="mt-3 grid gap-2 md:grid-cols-2">
                {supportedDatasetFormats.map(([format, purpose]) => (
                  <div key={format} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-700">
                    <span className="font-mono text-xs font-semibold text-slate-900">{format}</span>
                    <span className="ml-2">{purpose}</span>
                  </div>
                ))}
              </div>
            </div>
            <div className="mt-4 rounded-2xl border border-indigo-200 bg-indigo-50 p-4">
              <div className={labelClass}>Post-capture dataset/export formats</div>
              <p className="mt-2 text-sm leading-6 text-indigo-950">
                Capture Lab acquires only raw SDR evidence as `.cfile` or `.iq`. The buttons below call RF Experiment Lab backend
                exporters to derive SigMF, HDF5 manifests, NumPy representation artifacts, spectrogram and waterfall packages from
                the same IQ file and metadata.
              </p>
              <div className="mt-4 grid gap-2 md:grid-cols-4">
                <button type="button" className="rounded-xl border border-indigo-300 bg-white px-3 py-2 text-xs font-semibold text-indigo-900" onClick={() => runPostCaptureExport('sigmf_preview')}>SigMF preview</button>
                <button type="button" className="rounded-xl border border-indigo-300 bg-white px-3 py-2 text-xs font-semibold text-indigo-900" onClick={() => runPostCaptureExport('sigmf_export')}>Export SigMF</button>
                <button type="button" className="rounded-xl border border-indigo-300 bg-white px-3 py-2 text-xs font-semibold text-indigo-900" onClick={() => runPostCaptureExport('hdf5_preview')}>HDF5 manifest preview</button>
                <button type="button" className="rounded-xl border border-indigo-300 bg-white px-3 py-2 text-xs font-semibold text-indigo-900" onClick={() => runPostCaptureExport('hdf5_export')}>Export HDF5 manifest</button>
                <button type="button" className="rounded-xl border border-indigo-300 bg-white px-3 py-2 text-xs font-semibold text-indigo-900" onClick={() => runPostCaptureExport('raw-iq')}>Export raw_iq .npy</button>
                <button type="button" className="rounded-xl border border-indigo-300 bg-white px-3 py-2 text-xs font-semibold text-indigo-900" onClick={() => runPostCaptureExport('fft-psd')}>Export FFT/PSD .npy</button>
                <button type="button" className="rounded-xl border border-indigo-300 bg-white px-3 py-2 text-xs font-semibold text-indigo-900" onClick={() => runPostCaptureExport('spectrogram')}>Export spectrogram</button>
                <button type="button" className="rounded-xl border border-indigo-300 bg-white px-3 py-2 text-xs font-semibold text-indigo-900" onClick={() => runPostCaptureExport('waterfall')}>Export waterfall</button>
                <button type="button" className="rounded-xl border border-indigo-300 bg-white px-3 py-2 text-xs font-semibold text-indigo-900 md:col-span-2" onClick={() => runPostCaptureExport('manifest')}>Export representations_manifest.json</button>
                <button type="button" className="rounded-xl border border-amber-300 bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-900 md:col-span-2" onClick={() => setMessage('CSV spectral features are generated by the E5 Spectral Feature Baseline run as features.csv after RFExperimentDatasetV1 export.')}>CSV features via E5</button>
              </div>
              {postCaptureExport && (
                <pre className="mt-4 max-h-48 overflow-auto rounded-xl bg-white p-3 text-xs text-slate-700">
                  {JSON.stringify(postCaptureExport, null, 2)}
                </pre>
              )}
            </div>
            <div className="mt-4 grid gap-4 md:grid-cols-4">
              <label>
                <div className={labelClass}>LNA gain</div>
                <input className={inputClass} type="number" value={Number(form.capture_config.gain_settings.lna_db)} onChange={(e) => setGainSetting('lna_db', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>VGA gain</div>
                <input className={inputClass} type="number" value={Number(form.capture_config.gain_settings.vga_db)} onChange={(e) => setGainSetting('vga_db', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>IF gain</div>
                <input className={inputClass} type="number" value={Number(form.capture_config.gain_settings.if_db)} onChange={(e) => setGainSetting('if_db', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>Composite gain</div>
                <input className={inputClass} type="number" value={Number(form.capture_config.gain_settings.composite_gain_db)} onChange={(e) => setGainSetting('composite_gain_db', Number(e.target.value))} />
              </label>
            </div>
          </section>

          <section className={sectionClass}>
            <div className="mb-5 rounded-2xl border border-teal-200 bg-teal-50 p-4">
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div>
                  <div className={labelClass}>Automatic band-profile label</div>
                  <h2 className="mt-2 text-lg font-semibold text-slate-900">
                    {bandProfileSuggestion?.matched ? bandProfileSuggestion.defaults?.transmitter_label : 'Awaiting a confident profile match'}
                  </h2>
                  <p className="mt-2 max-w-3xl text-sm leading-6 text-teal-950">
                    Marker 1 y Marker 2 se comparan con <span className="font-mono">band_profiles.json</span>. El resultado se guarda como
                    etiqueta debil editable; para entrenamiento cientifico debes confirmarla como strong_label.
                  </p>
                </div>
                <div className="min-w-64 rounded-xl border border-teal-200 bg-white px-3 py-2 text-xs text-slate-700">
                  <div>Source: {markerBand ? 'Marker 1 / Marker 2' : 'current capture frequency'}</div>
                  <div>Profile: {bandProfileSuggestion?.profile_key ?? 'none'}</div>
                  <div>Score: {Number(bandProfileSuggestion?.score ?? 0).toFixed(3)}</div>
                </div>
              </div>
              <div className="mt-4 flex flex-wrap items-center gap-3">
                <label className="flex items-center gap-2 rounded-xl border border-teal-200 bg-white px-3 py-2 text-sm text-slate-700">
                  <input type="checkbox" checked={autoApplyBandProfile} onChange={(event) => setAutoApplyBandProfile(event.target.checked)} />
                  Auto-apply marker band defaults
                </label>
                <button type="button" className="rounded-xl border border-teal-300 bg-white px-3 py-2 text-sm font-semibold text-teal-900" onClick={() => applyBandProfileDefaults()}>
                  Apply detected defaults
                </button>
                <button
                  type="button"
                  className="rounded-xl border border-slate-300 bg-slate-950 px-3 py-2 text-sm font-semibold text-white"
                  onClick={() =>
                    setForm((current) => ({
                      ...current,
                      label_status: 'strong_label',
                      transmitter: {
                        ...current.transmitter,
                        ground_truth_confidence: 'operator_confirmed',
                      },
                    }))
                  }
                >
                  Confirm label as strong
                </button>
              </div>
              {(bandProfileSuggestion?.candidates?.length ?? 0) > 0 && (
                <div className="mt-4 grid gap-2 md:grid-cols-2">
                  {(bandProfileSuggestion?.candidates ?? []).slice(0, 4).map((candidate: Record<string, any>) => (
                    <div key={candidate.profile_key} className="rounded-xl border border-teal-100 bg-white px-3 py-2 text-xs text-slate-700">
                      <div className="font-semibold text-slate-900">{candidate.label}</div>
                      <div>{candidate.profile_key} · {candidate.family} · score {Number(candidate.score ?? 0).toFixed(3)}</div>
                    </div>
                  ))}
                </div>
              )}
            </div>
            <div className="grid gap-4 md:grid-cols-3">
              <label>
                <div className={labelClass}>Transmitter label</div>
                <input className={inputClass} value={form.transmitter.transmitter_label} onChange={(e) => { setAutoApplyBandProfile(false); setNested('transmitter', 'transmitter_label', e.target.value); }} />
              </label>
              <label>
                <div className={labelClass}>Class / family</div>
                <input className={inputClass} value={form.transmitter.transmitter_class} onChange={(e) => { setAutoApplyBandProfile(false); setNested('transmitter', 'transmitter_class', e.target.value); }} />
              </label>
              <label>
                <div className={labelClass}>Unique transmitter ID</div>
                <input className={inputClass} value={form.transmitter.transmitter_id} onChange={(e) => { setAutoApplyBandProfile(false); setNested('transmitter', 'transmitter_id', e.target.value); }} />
              </label>
              <label>
                <div className={labelClass}>Signal type</div>
                <input className={inputClass} value={form.transmitter.signal_type} onChange={(e) => { setAutoApplyBandProfile(false); setNested('transmitter', 'signal_type', e.target.value); }} />
              </label>
              <label>
                <div className={labelClass}>Modulation class</div>
                <input className={inputClass} value={form.transmitter.modulation_class} onChange={(e) => { setAutoApplyBandProfile(false); setNested('transmitter', 'modulation_class', e.target.value); }} />
              </label>
              <label>
                <div className={labelClass}>Band profile key</div>
                <input className={inputClass} value={form.transmitter.profile_key} onChange={(e) => { setAutoApplyBandProfile(false); setNested('transmitter', 'profile_key', e.target.value); }} />
              </label>
              <label>
                <div className={labelClass}>Session ID</div>
                <input className={inputClass} value={form.session_id} onChange={(e) => setForm((current) => ({ ...current, session_id: e.target.value }))} />
              </label>
              <label>
                <div className={labelClass}>Dataset split</div>
                <select className={inputClass} value={form.dataset_split} onChange={(e) => setDatasetSplit(e.target.value as 'train' | 'val' | 'predict')}>
                  <option value="train">train</option>
                  <option value="val">val</option>
                  <option value="predict">predict</option>
                </select>
              </label>
              <label>
                <div className={labelClass}>Operator</div>
                <input className={inputClass} value={form.scenario.operator} onChange={(e) => setNested('scenario', 'operator', e.target.value)} />
              </label>
              <label>
                <div className={labelClass}>Environment</div>
                <input className={inputClass} value={form.scenario.environment} onChange={(e) => setNested('scenario', 'environment', e.target.value)} />
              </label>
            </div>
            <label className="mt-4 block">
              <div className={labelClass}>Notes</div>
              <textarea className={`${inputClass} min-h-24`} value={form.scenario.notes} onChange={(e) => setNested('scenario', 'notes', e.target.value)} />
            </label>
          </section>

          <section className={sectionClass}>
            <div className="grid gap-4 md:grid-cols-4">
              <label>
                <div className={labelClass}>Estimated SNR (dB)</div>
                <input className={inputClass} type="number" value={form.quality_metrics.estimated_snr_db} onChange={(e) => setNested('quality_metrics', 'estimated_snr_db', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>Frequency offset (Hz)</div>
                <input className={inputClass} type="number" value={form.quality_metrics.frequency_offset_hz} onChange={(e) => setNested('quality_metrics', 'frequency_offset_hz', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>Clipping (%)</div>
                <input className={inputClass} type="number" value={form.quality_metrics.clipping_pct} onChange={(e) => setNested('quality_metrics', 'clipping_pct', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>Silence (%)</div>
                <input className={inputClass} type="number" value={form.quality_metrics.silence_pct} onChange={(e) => setNested('quality_metrics', 'silence_pct', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>Energy threshold (dB)</div>
                <input className={inputClass} type="number" value={form.burst_detection.energy_threshold_db ?? 0} onChange={(e) => setNested('burst_detection', 'energy_threshold_db', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>Pre-trigger samples</div>
                <input className={inputClass} type="number" value={form.burst_detection.pre_trigger_samples} onChange={(e) => setNested('burst_detection', 'pre_trigger_samples', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>Post-trigger samples</div>
                <input className={inputClass} type="number" value={form.burst_detection.post_trigger_samples} onChange={(e) => setNested('burst_detection', 'post_trigger_samples', Number(e.target.value))} />
              </label>
              <label>
                <div className={labelClass}>Burst duration (ms)</div>
                <input className={inputClass} type="number" value={form.quality_metrics.burst_duration_ms} onChange={(e) => setNested('quality_metrics', 'burst_duration_ms', Number(e.target.value))} />
              </label>
            </div>
            <label className="mt-4 block">
              <div className={labelClass}>IQ file</div>
              <input className={inputClass} value={form.artifacts.iq_file} onChange={(e) => setForm((current) => ({ ...current, artifacts: { ...current.artifacts, iq_file: e.target.value }, capture_config: { ...current.capture_config, output_path: e.target.value } }))} />
            </label>
            <label className="mt-4 block">
              <div className={labelClass}>Dataset destination</div>
              <input className={inputClass} value={form.capture_config.dataset_destination} onChange={(e) => setNested('capture_config', 'dataset_destination', e.target.value)} />
            </label>
            <div className="mt-5 flex flex-wrap gap-3">
              <button className="rounded-full bg-teal-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-teal-500" onClick={submit}>
                Save Scientific Manifest
              </button>
              <button className="rounded-full border border-indigo-300 bg-indigo-50 px-5 py-3 text-sm font-semibold text-indigo-800 transition hover:bg-indigo-100" onClick={saveRFExperimentSample}>
                Create RF Experiment Sample
              </button>
              <a className="rounded-full border border-slate-300 px-5 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-100" href="/spectrum">
                Open Live Monitor
              </a>
            </div>
            <div className="mt-4 rounded-2xl border border-indigo-200 bg-indigo-50 p-4 text-sm leading-6 text-indigo-950">
              Capture formats are intentionally limited to `.cfile` and `.iq` because Capture Lab stores raw SDR I/Q evidence.
              SigMF, HDF5, NumPy, CSV features and spectrogram/waterfall files are dataset export or representation formats generated later
              by RF Experiment Lab from the same raw I/Q evidence.
            </div>
          </section>
        </div>

        <div className="space-y-5">
          <section className={sectionClass}>
            <div className="mb-4 flex items-center justify-between">
              <div>
                <div className={labelClass}>Real IQ captures available</div>
                <div className="mt-1 text-sm text-slate-600">
                  Importa una captura ya adquirida en `Signal Analysis` y clasificala como train, val o predict.
                </div>
              </div>
            </div>
            <div className="space-y-3">
              {modulatedCaptures.map((capture) => (
                <div key={capture.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <div className="font-semibold text-slate-900">{capture.id}</div>
                      <div className="mt-1 text-xs text-slate-600">
                        {(capture.center_frequency_hz / 1e6).toFixed(6)} MHz · {(capture.bandwidth_hz / 1e3).toFixed(1)} kHz · {capture.duration_seconds}s
                      </div>
                      <div className="mt-1 text-xs text-slate-500">Will import as: {form.dataset_split}</div>
                    </div>
                    <button
                      className="rounded-full border border-teal-500 px-3 py-2 text-xs font-semibold text-teal-700 transition hover:bg-teal-50"
                      onClick={() => importCapture(capture)}
                    >
                      Import as fingerprint capture
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section className={sectionClass}>
            <div className="mb-4 flex items-center justify-between">
              <div className={labelClass}>Recent scientific captures</div>
              <div className="text-xs text-slate-500">{captures.length} manifests</div>
            </div>
            <div className="space-y-3">
              {captures.slice(0, 6).map((capture) => (
                <div key={capture.capture_id} className="rounded-2xl border border-slate-200 p-4">
                  <div className="flex items-center justify-between gap-3">
                    <div>
                      <div className="font-semibold text-slate-900">{capture.transmitter.transmitter_id}</div>
                      <div className="text-xs text-slate-600">
                        {capture.session_id} · {capture.dataset_split} · {capture.capture_config.dataset_destination}
                      </div>
                    </div>
                    <span
                      className={`rounded-full px-3 py-1 text-xs font-semibold ${
                        capture.quality_review.status === 'valid'
                          ? 'bg-emerald-100 text-emerald-700'
                          : capture.quality_review.status === 'doubtful'
                            ? 'bg-amber-100 text-amber-700'
                            : 'bg-rose-100 text-rose-700'
                      }`}
                    >
                      {capture.quality_review.status}
                    </span>
                  </div>
                  <div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-600">
                    <div>SNR: {capture.quality_metrics.estimated_snr_db ?? 0} dB</div>
                    <div>Offset: {capture.quality_metrics.frequency_offset_hz ?? 0} Hz</div>
                    <div>Clipping: {capture.quality_metrics.clipping_pct ?? 0}%</div>
                    <div>Burst: {capture.quality_metrics.burst_duration_ms ?? 0} ms</div>
                  </div>
                </div>
              ))}
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};
